CREATE TABLE GENERO (
  id SERIAL  NOT NULL ,
  nombre VARCHAR(60)    ,
  descripcion TEXT    ,
  fechaCreacion DATE      ,
PRIMARY KEY(id));




CREATE TABLE LIBRO (
  ISBN SERIAL  NOT NULL ,
  PORTADA BLOB    ,
  TITULO VARCHAR(60)    ,
  SIPNOSIS VARCHAR(300)    ,
  AUTOR VARCHAR(60)    ,
  EDITORIAL VARCHAR(60)    ,
  FECHA_PUBLICACION DATE    ,
  estadoLibro VARCHAR(60)    ,
  PRECIO DOUBLE      ,
PRIMARY KEY(ISBN));




CREATE TABLE CLIENTE (
  ID SERIAL  NOT NULL ,
  NOMBRE VARCHAR(60)    ,
  SEGUNDO_NOMBRE VARCHAR(60)    ,
  APELLIDO_PATERNO VARCHAR(60)    ,
  APELLIDO_MATERNO VARCHAR(60)    ,
  CEDULA VARCHAR(30)   NOT NULL ,
  DIRECCION VARCHAR(60)    ,
  TELEFONO VARCHAR(60)    ,
  PAIS VARCHAR(60)    ,
  CIUDAD VARCHAR(60)    ,
  CORREO VARCHAR(60)    ,
  FECHA_REGISTRO DATE      ,
PRIMARY KEY(ID));




CREATE TABLE EMPLEADO (
  ID SERIAL  NOT NULL ,
  FOTO BLOB    ,
  NOMBRE VARCHAR(60)    ,
  SEGUNDO_NOMBRE VARCHAR(60)    ,
  APELLIDO_PATERNO VARCHAR(60)    ,
  APELLIDO_MATERNO VARCHAR(60)    ,
  CEDULA VARCHAR(60)   NOT NULL ,
  DIRECCION VARCHAR(60)    ,
  PAIS VARCHAR(60)    ,
  CIUDAD VARCHAR(60)    ,
  CORREO VARCHAR(60)    ,
  TELEFONO VARCHAR(30)    ,
  FECHA_CONTRATO DATE    ,
  CARGO VARCHAR(60)    ,
  SALARIO DOUBLE   NOT NULL   ,
PRIMARY KEY(ID));




CREATE TABLE USUARIO (
  id SERIAL  NOT NULL ,
  EMPLEADO_ID INTEGER   NOT NULL ,
  usuario VARCHAR(60)    ,
  contraseña VARCHAR(60)    ,
  estado BOOL      ,
PRIMARY KEY(id)  ,
  FOREIGN KEY(EMPLEADO_ID)
    REFERENCES EMPLEADO(ID));


CREATE INDEX USUARIO_FKIndex1 ON USUARIO (EMPLEADO_ID);



CREATE INDEX IFK_Rel_14 ON USUARIO (EMPLEADO_ID);


CREATE TABLE ordenPrestamo (
  numeroOrden SERIAL  NOT NULL ,
  EMPLEADO_ID INTEGER   NOT NULL ,
  CLIENTE_ID INTEGER   NOT NULL ,
  fechaOrden DATE    ,
  fechaEntreha DATE    ,
  cantidadTotal INTEGER      ,
PRIMARY KEY(numeroOrden)    ,
  FOREIGN KEY(CLIENTE_ID)
    REFERENCES CLIENTE(ID),
  FOREIGN KEY(EMPLEADO_ID)
    REFERENCES EMPLEADO(ID));


CREATE INDEX ordenPrestamo_FKIndex1 ON ordenPrestamo (CLIENTE_ID);
CREATE INDEX ordenPrestamo_FKIndex2 ON ordenPrestamo (EMPLEADO_ID);


CREATE INDEX IFK_Rel_10 ON ordenPrestamo (CLIENTE_ID);
CREATE INDEX IFK_Rel_11 ON ordenPrestamo (EMPLEADO_ID);


CREATE TABLE ordenItemPrestamo (
  LIBRO_ISBN INTEGER   NOT NULL ,
  ordenPrestamo_numeroOrden INTEGER   NOT NULL ,
  estadoLibro VARCHAR(60)    ,
  estadoOrden VARCHAR(60)      ,
PRIMARY KEY(LIBRO_ISBN, ordenPrestamo_numeroOrden)    ,
  FOREIGN KEY(LIBRO_ISBN)
    REFERENCES LIBRO(ISBN),
  FOREIGN KEY(ordenPrestamo_numeroOrden)
    REFERENCES ordenPrestamo(numeroOrden));


CREATE INDEX LIBRO_has_ordenPrestamo_FKIndex1 ON ordenItemPrestamo (LIBRO_ISBN);
CREATE INDEX LIBRO_has_ordenPrestamo_FKIndex2 ON ordenItemPrestamo (ordenPrestamo_numeroOrden);


CREATE INDEX IFK_Rel_07 ON ordenItemPrestamo (LIBRO_ISBN);
CREATE INDEX IFK_Rel_08 ON ordenItemPrestamo (ordenPrestamo_numeroOrden);


CREATE TABLE GENERO_LIBROS (
  GENERO_id INTEGER   NOT NULL ,
  LIBRO_ISBN INTEGER   NOT NULL   ,
PRIMARY KEY(GENERO_id, LIBRO_ISBN)    ,
  FOREIGN KEY(GENERO_id)
    REFERENCES GENERO(id),
  FOREIGN KEY(LIBRO_ISBN)
    REFERENCES LIBRO(ISBN));


CREATE INDEX GENERO_has_LIBRO_FKIndex1 ON GENERO_LIBROS (GENERO_id);
CREATE INDEX GENERO_has_LIBRO_FKIndex2 ON GENERO_LIBROS (LIBRO_ISBN);


CREATE INDEX IFK_Rel_09 ON GENERO_LIBROS (GENERO_id);
CREATE INDEX IFK_Rel_10 ON GENERO_LIBROS (LIBRO_ISBN);


CREATE TABLE ordenCompra (
  numeroOrden SERIAL  NOT NULL ,
  EMPLEADO_ID INTEGER   NOT NULL ,
  CLIENTE_ID INTEGER   NOT NULL ,
  fechaOrden DATE    ,
  cantidadTotal DOUBLE    ,
  precioTotal DOUBLE      ,
PRIMARY KEY(numeroOrden)    ,
  FOREIGN KEY(CLIENTE_ID)
    REFERENCES CLIENTE(ID),
  FOREIGN KEY(EMPLEADO_ID)
    REFERENCES EMPLEADO(ID));


CREATE INDEX ordenCompra_FKIndex1 ON ordenCompra (CLIENTE_ID);
CREATE INDEX ordenCompra_FKIndex2 ON ordenCompra (EMPLEADO_ID);


CREATE INDEX IFK_Rel_01 ON ordenCompra (CLIENTE_ID);
CREATE INDEX IFK_Rel_03 ON ordenCompra (EMPLEADO_ID);


CREATE TABLE ordenItem (
  ordenCompra_numeroOrden INTEGER   NOT NULL ,
  LIBRO_ISBN INTEGER   NOT NULL ,
  cantidadOrden INTEGER    ,
  valorOrden DOUBLE      ,
PRIMARY KEY(ordenCompra_numeroOrden, LIBRO_ISBN)    ,
  FOREIGN KEY(ordenCompra_numeroOrden)
    REFERENCES ordenCompra(numeroOrden),
  FOREIGN KEY(LIBRO_ISBN)
    REFERENCES LIBRO(ISBN));


CREATE INDEX ordenCompra_has_LIBRO_FKIndex1 ON ordenItem (ordenCompra_numeroOrden);
CREATE INDEX ordenCompra_has_LIBRO_FKIndex2 ON ordenItem (LIBRO_ISBN);


CREATE INDEX IFK_Rel_07 ON ordenItem (ordenCompra_numeroOrden);
CREATE INDEX IFK_Rel_08 ON ordenItem (LIBRO_ISBN);


CREATE TABLE ROL_USUARIO (
  id SERIAL not null,
  USUARIO_id INTEGER   NOT NULL ,
  nombreRol VARCHAR(60)    ,
  fechaCreacion DATE    ,
  nombreTabla VARCHAR    ,
  ver BOOL    ,
  insertar BOOL    ,
  editar BOOL    ,
  borrar BOOL      ,
PRIMARY KEY(id)  ,
  FOREIGN KEY(USUARIO_id)
    REFERENCES USUARIO(id));



