/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.Cliente;
import MODELO.Empleado;
import MODELO.Libro;
import MODELO.Ordencompra;
import MODELO.Ordenitem;
import MODELO.OrdenitemPK;
import MODELO_CONTROLADOR.MC_Cliente;
import MODELO_CONTROLADOR.MC_Empleado;
import MODELO_CONTROLADOR.MC_Libro;
import MODELO_CONTROLADOR.MC_OrdenCompra;
import MODELO_CONTROLADOR.MC_OrdenItem;
import MODELO_CONTROLADOR.funciones;
import com.toedter.calendar.JCalendar;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ayenni42
 */
public class ventanaOrdenCompra extends javax.swing.JDialog {

    /**
     * Funciones de la clase numeroOrden -> obtener el numero que se la va a dar
     * a la factura obtenerElementos -> obtener la informacion de las cajas de
     * texto de la ventana mostrar libros -> recibe una lista de libros y los
     * pone en la tabla de item pidiento la cantidad de libros que se van a
     * comprar
     */
    //variable que guarda la informacion del empleado 
    Empleado empleado;
    //variable para guardar la informacion del cliente 
    Cliente cliente;
    //variable para guardar la informacion de la orden de compra
    Ordencompra ordenCompra;
    //variable de los libros a comprar
    List<Libro> libroOrden;
    //variable de los Item a comprar 
    List<Ordenitem> ordenItem = new ArrayList<>();
    // modelo de la tablaOrdenCompra
    DefaultTableModel modeloTablaItem;

    public ventanaOrdenCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(600, 570);

        entNombreEmpledo.setBackground(Color.WHITE);
        entApellidoEmpleado.setBackground(Color.WHITE);
        entTelefonoEmpleado.setBackground(Color.WHITE);
        entCedulaEmpleado.setBackground(Color.WHITE);
        entNombreCliente.setBackground(Color.WHITE);
        entApellidoCliente.setBackground(Color.WHITE);
        entTelefonoCliente.setBackground(Color.WHITE);
        entCedulaCliente.setBackground(Color.WHITE);
        entNumeroOrden.setBackground(Color.WHITE);

        modeloTablaItem = (DefaultTableModel) tablaOrdenCompra.getModel();

        JCalendar calendario = entFechaOrden.getJCalendar();
        calendario.setWeekOfYearVisible(false);
        calendario.setMaxDayCharacters(2);
        entFechaOrden.setDate(funciones.fecha());
        //numeroOrden();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        entNombreEmpledo = new javax.swing.JTextField();
        entTelefonoEmpleado = new javax.swing.JTextField();
        entCedulaEmpleado = new javax.swing.JTextField();
        entApellidoEmpleado = new javax.swing.JTextField();
        btnBuscarEmpleado = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        entNombreCliente = new javax.swing.JTextField();
        entTelefonoCliente = new javax.swing.JTextField();
        entCedulaCliente = new javax.swing.JTextField();
        entApellidoCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        entNumeroOrden = new javax.swing.JTextField();
        entFechaOrden = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOrdenCompra = new javax.swing.JTable();
        entCantidadTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        entPrecioTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 570));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255)));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Orden De Compra");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(5, 0, 150, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informacion Empleado", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Nombre ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(4, 20, 50, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Apellido");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(254, 20, 50, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Cedula");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(4, 55, 50, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Telefono");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(254, 55, 50, 30);

        entNombreEmpledo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        entNombreEmpledo.setEnabled(false);
        jPanel2.add(entNombreEmpledo);
        entNombreEmpledo.setBounds(59, 20, 180, 30);

        entTelefonoEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        entTelefonoEmpleado.setEnabled(false);
        jPanel2.add(entTelefonoEmpleado);
        entTelefonoEmpleado.setBounds(309, 55, 180, 30);

        entCedulaEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        entCedulaEmpleado.setEnabled(false);
        jPanel2.add(entCedulaEmpleado);
        entCedulaEmpleado.setBounds(59, 55, 180, 30);

        entApellidoEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        entApellidoEmpleado.setEnabled(false);
        jPanel2.add(entApellidoEmpleado);
        entApellidoEmpleado.setBounds(309, 20, 180, 30);

        btnBuscarEmpleado.setText("Busca");
        btnBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarEmpleado);
        btnBuscarEmpleado.setBounds(490, 17, 70, 70);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(5, 75, 564, 90);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informacion Cliente", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel4.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Nombre ");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(4, 20, 50, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Apellido");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(254, 20, 50, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Cedula");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(4, 55, 50, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Telefono");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(254, 55, 50, 30);

        entNombreCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        entNombreCliente.setEnabled(false);
        jPanel4.add(entNombreCliente);
        entNombreCliente.setBounds(59, 20, 180, 30);

        entTelefonoCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        entTelefonoCliente.setEnabled(false);
        jPanel4.add(entTelefonoCliente);
        entTelefonoCliente.setBounds(309, 55, 180, 30);

        entCedulaCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        entCedulaCliente.setEnabled(false);
        jPanel4.add(entCedulaCliente);
        entCedulaCliente.setBounds(59, 55, 180, 30);

        entApellidoCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        entApellidoCliente.setEnabled(false);
        jPanel4.add(entApellidoCliente);
        entApellidoCliente.setBounds(309, 20, 180, 30);

        btnBuscarCliente.setText("Busca");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        jPanel4.add(btnBuscarCliente);
        btnBuscarCliente.setBounds(490, 17, 70, 70);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(5, 170, 564, 90);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Fecha Orden");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(289, 5, 80, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Numero Orden");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(35, 5, 90, 30);

        entNumeroOrden.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        entNumeroOrden.setEnabled(false);
        jPanel3.add(entNumeroOrden);
        entNumeroOrden.setBounds(130, 5, 155, 30);

        entFechaOrden.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(entFechaOrden);
        entFechaOrden.setBounds(374, 5, 155, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(5, 30, 564, 40);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        tablaOrdenCompra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tablaOrdenCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Isbn", "Titulo", "Precio C/U", "cantidad", "Precio Total"
            }
        ));
        jScrollPane1.setViewportView(tablaOrdenCompra);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(5, 5, 480, 200);

        entCantidadTotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel5.add(entCantidadTotal);
        entCantidadTotal.setBounds(105, 210, 140, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Cantidad Total");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(10, 210, 90, 30);

        entPrecioTotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel5.add(entPrecioTotal);
        entPrecioTotal.setBounds(329, 210, 155, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Precio Total");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(254, 210, 80, 30);

        btnEditar.setText("Edit");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel5.add(btnEditar);
        btnEditar.setBounds(490, 100, 70, 70);

        btnGuardar.setText("guar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel5.add(btnGuardar);
        btnGuardar.setBounds(490, 175, 70, 70);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(490, 50, 73, 23);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(5, 265, 564, 250);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(160, 15, 410, 2);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(5, 5, 575, 522);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarElemetnosCliente(Cliente cliente) {
        limpiarCliente();
        if (cliente != null) {
            if (cliente.getNombre() == null || cliente.getNombre().isEmpty()) {
                entNombreCliente.setText("Sin Nombre");
            } else {
                entNombreCliente.setText(cliente.getNombre());
            }
            if (cliente.getApellidoPaterno() == null || cliente.getApellidoPaterno().isEmpty()) {
                entApellidoCliente.setText("Sin Apellido");
            } else {
                entApellidoCliente.setText(cliente.getApellidoPaterno());
            }
            if (cliente.getTelefono() == null || cliente.getTelefono().isEmpty()) {
                entTelefonoCliente.setText("Sin Telefono");
            } else {
                entTelefonoCliente.setText(cliente.getTelefono());
            }
            if (cliente.getCedula() == null || cliente.getCedula().isEmpty()) {
                entCedulaCliente.setText("Sin Cedula");
            } else {
                entCedulaCliente.setText(cliente.getCedula());
            }
        } else {
            JOptionPane.showMessageDialog(this, "No Se Encontro El Cliente", "Informacion", 1, null);
        }
    }

    public void mostrarElementosOrdenCompra(Ordencompra orden) {
        Cliente clienteOrden = orden.getClienteId();
        Empleado empleadoOrden = orden.getEmpleadoId();
        entNumeroOrden.setText(String.valueOf(orden.getNumeroorden()));
        entFechaOrden.setDate(orden.getFechaorden());
        entPrecioTotal.setText(String.valueOf(orden.getPreciototal()));
        entCantidadTotal.setText(String.valueOf(orden.getCantidadtotal()));
        mostrarElemetnosCliente(clienteOrden);
        mostrarElementosEmpleado(empleadoOrden);
    }

    public void limpiarOrden() {
        numeroOrden();
        entFechaOrden.setDate(funciones.fecha());
        entPrecioTotal.setText("");
        entCantidadTotal.setText("");
        limpiarCliente();
        limpiarEmpleado();
    }

    public void limpiarCliente() {
        entNombreCliente.setText("");
        entApellidoCliente.setText("");
        entTelefonoCliente.setText("");
        entCedulaCliente.setText("");
    }

    public void limpiarEmpleado() {
        entNombreEmpledo.setText("");
        entApellidoEmpleado.setText("");
        entTelefonoEmpleado.setText("");
        entCedulaEmpleado.setText("");
    }

    public void mostrarElementosEmpleado(Empleado empleado) {
        limpiarEmpleado();
        if (empleado != null) {
            if (empleado.getNombre() == null || empleado.getNombre().isEmpty()) {
                entNombreEmpledo.setText("Sin Nombre");
            } else {
                entNombreEmpledo.setText(empleado.getNombre());
            }
            if (empleado.getApellidoPaterno() == null || empleado.getApellidoPaterno().isEmpty()) {
                entApellidoEmpleado.setText("Sin Apellido");
            } else {
                entApellidoEmpleado.setText(empleado.getApellidoPaterno());
            }
            if (empleado.getTelefono() == null || empleado.getTelefono().isEmpty()) {
                entTelefonoEmpleado.setText("Sin Telefono");
            } else {
                entTelefonoEmpleado.setText(empleado.getTelefono());
            }
            if (empleado.getCedula() == null || empleado.getCedula().isEmpty()) {
                entCedulaEmpleado.setText("Sin Cedula");
            } else {
                entCedulaEmpleado.setText(empleado.getCedula());
            }
        } else {
            JOptionPane.showMessageDialog(this, "No Se Encontro El Empleado", "Informacion", 1, null);
        }
    }
    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        limpiarCliente();
        cliente = null;
        MC_Cliente control = new MC_Cliente();
        cliente = control.buscarCliente(Integer.parseInt(JOptionPane.showInputDialog("Id Del Cliente")));
        mostrarElemetnosCliente(cliente);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoActionPerformed
        limpiarEmpleado();
        empleado = null;
        MC_Empleado control = new MC_Empleado();
        empleado = control.buscarEmpleado(Integer.parseInt(JOptionPane.showInputDialog("Id Del Empleado")));
        mostrarElementosEmpleado(empleado);
    }//GEN-LAST:event_btnBuscarEmpleadoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ordenCompra = new Ordencompra();
        obtenerElemntos();

        if (!ordenItem.isEmpty()) {

            if (JOptionPane.showConfirmDialog(this, "Guardar Orden De Compra", "Escudo", 1, 3, null) == 0) {
                //Almacenar la orden de compra
                MC_OrdenCompra controlCompra = new MC_OrdenCompra();
                if (controlCompra.nuevaOrdenCompra(ordenCompra)) {
                    MC_OrdenItem controlItem = new MC_OrdenItem();
                    //Almacenar Los Item de la orden
                    for (Ordenitem item : ordenItem) {
                        item.setOrdencompra(ordenCompra);
                        controlItem.nuevaOrdenItem(item);
                    }
                    controlCompra.close();
                    controlItem.close();
                    JOptionPane.showMessageDialog(this, "Orden De Compra Almacenada", "Informacion", 1, null);
                    limpiarOrden();
                } else {
                    controlCompra.close();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No Se A Seleccionado Ningun Item", "Informacion", 1, null);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        obtenerElemntos();
        if (JOptionPane.showConfirmDialog(this, "Editar Orden De Compra", "Escudo", 1, 3, null) == 0) {
            //Editar la orden de compra
            MC_OrdenCompra controlCompra = new MC_OrdenCompra();
            if (controlCompra.editarOrdenCompra(ordenCompra)) {
                controlCompra.close();
                JOptionPane.showMessageDialog(this, "Orden De Compra Editada", "Informacion", 1, null);
                limpiarOrden();
            } else {
                controlCompra.close();
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MC_Libro contro = new MC_Libro();
        List<Libro> ordenItem3 = new ArrayList<>();
        ordenItem3.add(contro.buscarLibro(1));
        ordenItem3.add(contro.buscarLibro(2));
        contro.close();
        //Actualiza la  lista de orden de item para modificar 
        mostraLibro(ordenItem3);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void numeroOrden() {
        int numeroOrden;
        MC_OrdenCompra control = new MC_OrdenCompra();
        List<Ordencompra> ordenCom = control.buscarTodasOrdenesCompra();
        if (ordenCom.isEmpty()) {
            numeroOrden = 1;
        } else {
            numeroOrden = ordenCom.get(ordenCom.size() - 1).getNumeroorden() + 1;
        }
        entNumeroOrden.setText(String.valueOf(numeroOrden));
    }

    public void obtenerElemntos() {
        ordenCompra.setFechaorden(entFechaOrden.getDate());
        ordenCompra.setPreciototal(Integer.parseInt(entPrecioTotal.getText()));
        ordenCompra.setCantidadtotal(Integer.parseInt(entCantidadTotal.getText()));
        ordenCompra.setClienteId(cliente);
        ordenCompra.setEmpleadoId(empleado);
    }

    public void mostraLibro(List<Libro> libros) {
        int cantidadTotal = 0;
        int precioTotal = 0;

        for (Libro libro : libros) {

            int isbn = libro.getIsbn();
            String titulo = "Sin Titulo";
            int precio = 0;
            int cantidad = 1;

            if (!libro.getTitulo().isEmpty()) {
                titulo = libro.getTitulo();
            }
            if (libro.getPrecio() > 0) {
                precio = libro.getPrecio();
            }

            String entrada = JOptionPane.showInputDialog("Cuantos Libros Desea Comprar \nTitulo Del Libro: " + titulo);

            if (!entrada.isEmpty()) {
                cantidad = Integer.parseInt(entrada);
            }
            int precioTotalLibro = cantidad * precio;
            Ordenitem ordenI = new Ordenitem(cantidad, precioTotalLibro, libro);
            ordenItem.add(ordenI);
            modeloTablaItem.addRow(new Object[]{isbn, titulo, precio, cantidad, precioTotalLibro});
            cantidadTotal += cantidad;
            precioTotal += precioTotalLibro;
        }
        entCantidadTotal.setText(String.valueOf(cantidadTotal));
        entPrecioTotal.setText(String.valueOf(precioTotal));
    }

    public void mostraItem(List<Ordenitem> items) {
        for (Ordenitem item : items) {
            Libro libro = item.getLibro();
            int isbn = libro.getIsbn();
            String titulo = "Sin Titulo";
            int precio = 0;
            int cantidad = 1;

            if (!libro.getTitulo().isEmpty()) {
                titulo = libro.getTitulo();
            }
            if (libro.getPrecio() > 0) {
                precio = libro.getPrecio();
            }
            cantidad = item.getCantidadorden();
            int precioTotalLibro = item.getValororden();
            ordenItem.add(item);
            modeloTablaItem.addRow(new Object[]{isbn, titulo, precio, cantidad, precioTotalLibro});
        }
    }

    public Empleado getEmpleado() {
        return empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public List<Libro> getLibroOrden() {
        return libroOrden;
    }

    public void setLibroOrden(List<Libro> libroOrden) {
        this.libroOrden = libroOrden;
    }

    public List<Ordenitem> getOrdenItem() {
        return ordenItem;
    }

    public void setOrdenItem(List<Ordenitem> ordenItem) {
        this.ordenItem = ordenItem;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaOrdenCompra dialog = new ventanaOrdenCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarEmpleado;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField entApellidoCliente;
    private javax.swing.JTextField entApellidoEmpleado;
    private javax.swing.JTextField entCantidadTotal;
    private javax.swing.JTextField entCedulaCliente;
    private javax.swing.JTextField entCedulaEmpleado;
    private com.toedter.calendar.JDateChooser entFechaOrden;
    private javax.swing.JTextField entNombreCliente;
    private javax.swing.JTextField entNombreEmpledo;
    private javax.swing.JTextField entNumeroOrden;
    private javax.swing.JTextField entPrecioTotal;
    private javax.swing.JTextField entTelefonoCliente;
    private javax.swing.JTextField entTelefonoEmpleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablaOrdenCompra;
    // End of variables declaration//GEN-END:variables
}
