/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.Permiso;
import MODELO.RolUsuario;
import java.util.Date;

/**
 *                      Funciones De La  ventanaRoles
 * obtenerElementos -> obtener la informacion de la caja de texto de la ventana 
 */
public class ventanaRoles extends javax.swing.JDialog {
/**
 * Variable Caso
 * 0 = No Hay Problemas 
 * 1 = Nombre De Rol Vacio 
 */
    int caso = 0;
    //Permisos De Roles 
    Permiso Cliente = new Permiso();
    Permiso Empleado = new Permiso();
    Permiso Usuario = new Permiso();
    Permiso Libro = new Permiso();
    Permiso OrdenCompra = new Permiso();
    Permiso OrdenPrestamo = new Permiso();
    Permiso Roles = new Permiso();
    Permiso Genero = new Permiso();
    
    public ventanaRoles(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        entUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        entRol = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        entFechaRegistro = new com.toedter.calendar.JDateChooser();
        fondoPermisos = new javax.swing.JPanel();
        fondoEmpleado = new javax.swing.JPanel();
        btnEmpleado = new javax.swing.JRadioButton();
        btnEmpleadoInsertar = new javax.swing.JRadioButton();
        btnEmpleadoEditar = new javax.swing.JRadioButton();
        btnEmpleadoVer = new javax.swing.JRadioButton();
        jSeparator9 = new javax.swing.JSeparator();
        fondoCliente = new javax.swing.JPanel();
        btnCliente = new javax.swing.JRadioButton();
        btnClienteInsertar = new javax.swing.JRadioButton();
        btnClienteEditar = new javax.swing.JRadioButton();
        btnClienteVer = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        fondoLibro = new javax.swing.JPanel();
        btnLibro = new javax.swing.JRadioButton();
        btnLibroInsertar = new javax.swing.JRadioButton();
        btnLibroEditar = new javax.swing.JRadioButton();
        btnLibroVer = new javax.swing.JRadioButton();
        jSeparator5 = new javax.swing.JSeparator();
        fondoOrdenPrestamo = new javax.swing.JPanel();
        btnOrdenPrestamo = new javax.swing.JRadioButton();
        btnOrdenPrestamoInsertar = new javax.swing.JRadioButton();
        btnOrdenPrestamoEditar = new javax.swing.JRadioButton();
        btnOrdenCompraVer = new javax.swing.JRadioButton();
        jSeparator7 = new javax.swing.JSeparator();
        fondoUsuario = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JRadioButton();
        btnUsuarioInsertar = new javax.swing.JRadioButton();
        btnUsuarioEditar = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        fondoRoles = new javax.swing.JPanel();
        btnRoles = new javax.swing.JRadioButton();
        btnRolesInsertar = new javax.swing.JRadioButton();
        btnRolesEditar = new javax.swing.JRadioButton();
        jSeparator4 = new javax.swing.JSeparator();
        fondoGenero = new javax.swing.JPanel();
        btnGenero = new javax.swing.JRadioButton();
        btnGeneroInsertar = new javax.swing.JRadioButton();
        btnGeneroEditar = new javax.swing.JRadioButton();
        jSeparator8 = new javax.swing.JSeparator();
        fondoOrdenCompra = new javax.swing.JPanel();
        btnOrdenCompra = new javax.swing.JRadioButton();
        btnOrdenCompraInsertar = new javax.swing.JRadioButton();
        btnOrdenCompraEditar = new javax.swing.JRadioButton();
        jSeparator6 = new javax.swing.JSeparator();
        foto = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255)));
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Usuario");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(170, 20, 70, 30);

        entUsuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(entUsuario);
        entUsuario.setBounds(240, 20, 285, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Rol");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 60, 40, 30);

        entRol.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(entRol);
        entRol.setBounds(240, 60, 285, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Fecha Registro ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 100, 130, 30);
        jPanel1.add(entFechaRegistro);
        entFechaRegistro.setBounds(290, 100, 235, 30);

        fondoPermisos.setBackground(new java.awt.Color(204, 204, 204));
        fondoPermisos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255)), "Permisos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 24))); // NOI18N
        fondoPermisos.setLayout(null);

        fondoEmpleado.setBackground(new java.awt.Color(153, 153, 153));
        fondoEmpleado.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255)));
        fondoEmpleado.setLayout(null);

        btnEmpleado.setBackground(new java.awt.Color(153, 153, 153));
        btnEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEmpleado.setText("Empleado");
        fondoEmpleado.add(btnEmpleado);
        btnEmpleado.setBounds(5, 5, 100, 30);

        btnEmpleadoInsertar.setBackground(new java.awt.Color(153, 153, 153));
        btnEmpleadoInsertar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEmpleadoInsertar.setText("Insertar");
        fondoEmpleado.add(btnEmpleadoInsertar);
        btnEmpleadoInsertar.setBounds(5, 45, 80, 30);

        btnEmpleadoEditar.setBackground(new java.awt.Color(153, 153, 153));
        btnEmpleadoEditar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEmpleadoEditar.setText("Editar");
        fondoEmpleado.add(btnEmpleadoEditar);
        btnEmpleadoEditar.setBounds(5, 80, 80, 30);

        btnEmpleadoVer.setBackground(new java.awt.Color(153, 153, 153));
        btnEmpleadoVer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEmpleadoVer.setText("Ver");
        fondoEmpleado.add(btnEmpleadoVer);
        btnEmpleadoVer.setBounds(5, 115, 80, 30);
        fondoEmpleado.add(jSeparator9);
        jSeparator9.setBounds(4, 40, 110, 2);

        fondoPermisos.add(fondoEmpleado);
        fondoEmpleado.setBounds(10, 30, 120, 155);

        fondoCliente.setBackground(new java.awt.Color(153, 153, 153));
        fondoCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255)));
        fondoCliente.setLayout(null);

        btnCliente.setBackground(new java.awt.Color(153, 153, 153));
        btnCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCliente.setText("Cliente");
        fondoCliente.add(btnCliente);
        btnCliente.setBounds(5, 5, 80, 30);

        btnClienteInsertar.setBackground(new java.awt.Color(153, 153, 153));
        btnClienteInsertar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnClienteInsertar.setText("Insertar");
        fondoCliente.add(btnClienteInsertar);
        btnClienteInsertar.setBounds(5, 45, 80, 30);

        btnClienteEditar.setBackground(new java.awt.Color(153, 153, 153));
        btnClienteEditar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnClienteEditar.setText("Editar");
        fondoCliente.add(btnClienteEditar);
        btnClienteEditar.setBounds(5, 80, 80, 30);

        btnClienteVer.setBackground(new java.awt.Color(153, 153, 153));
        btnClienteVer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnClienteVer.setText("Ver");
        fondoCliente.add(btnClienteVer);
        btnClienteVer.setBounds(5, 115, 80, 30);
        fondoCliente.add(jSeparator1);
        jSeparator1.setBounds(5, 40, 110, 10);

        fondoPermisos.add(fondoCliente);
        fondoCliente.setBounds(135, 30, 120, 155);

        fondoLibro.setBackground(new java.awt.Color(153, 153, 153));
        fondoLibro.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255)));
        fondoLibro.setLayout(null);

        btnLibro.setBackground(new java.awt.Color(153, 153, 153));
        btnLibro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnLibro.setText("Libros");
        fondoLibro.add(btnLibro);
        btnLibro.setBounds(5, 5, 80, 30);

        btnLibroInsertar.setBackground(new java.awt.Color(153, 153, 153));
        btnLibroInsertar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnLibroInsertar.setText("Insertar");
        fondoLibro.add(btnLibroInsertar);
        btnLibroInsertar.setBounds(5, 45, 80, 30);

        btnLibroEditar.setBackground(new java.awt.Color(153, 153, 153));
        btnLibroEditar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnLibroEditar.setText("Editar");
        fondoLibro.add(btnLibroEditar);
        btnLibroEditar.setBounds(5, 80, 80, 30);

        btnLibroVer.setBackground(new java.awt.Color(153, 153, 153));
        btnLibroVer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnLibroVer.setText("Ver");
        fondoLibro.add(btnLibroVer);
        btnLibroVer.setBounds(5, 115, 80, 30);
        fondoLibro.add(jSeparator5);
        jSeparator5.setBounds(4, 40, 80, 2);

        fondoPermisos.add(fondoLibro);
        fondoLibro.setBounds(260, 30, 90, 155);

        fondoOrdenPrestamo.setBackground(new java.awt.Color(153, 153, 153));
        fondoOrdenPrestamo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255)));
        fondoOrdenPrestamo.setLayout(null);

        btnOrdenPrestamo.setBackground(new java.awt.Color(153, 153, 153));
        btnOrdenPrestamo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnOrdenPrestamo.setText("Orden Prestamo");
        fondoOrdenPrestamo.add(btnOrdenPrestamo);
        btnOrdenPrestamo.setBounds(5, 5, 143, 30);

        btnOrdenPrestamoInsertar.setBackground(new java.awt.Color(153, 153, 153));
        btnOrdenPrestamoInsertar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnOrdenPrestamoInsertar.setText("Insertar");
        fondoOrdenPrestamo.add(btnOrdenPrestamoInsertar);
        btnOrdenPrestamoInsertar.setBounds(5, 45, 80, 30);

        btnOrdenPrestamoEditar.setBackground(new java.awt.Color(153, 153, 153));
        btnOrdenPrestamoEditar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnOrdenPrestamoEditar.setText("Editar");
        fondoOrdenPrestamo.add(btnOrdenPrestamoEditar);
        btnOrdenPrestamoEditar.setBounds(5, 80, 80, 30);

        btnOrdenCompraVer.setBackground(new java.awt.Color(153, 153, 153));
        btnOrdenCompraVer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnOrdenCompraVer.setText("Ver");
        fondoOrdenPrestamo.add(btnOrdenCompraVer);
        btnOrdenCompraVer.setBounds(5, 115, 80, 30);
        fondoOrdenPrestamo.add(jSeparator7);
        jSeparator7.setBounds(5, 40, 110, 2);

        fondoPermisos.add(fondoOrdenPrestamo);
        fondoOrdenPrestamo.setBounds(355, 30, 150, 155);

        fondoUsuario.setBackground(new java.awt.Color(153, 153, 153));
        fondoUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255)));

        btnUsuario.setBackground(new java.awt.Color(153, 153, 153));
        btnUsuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnUsuario.setText("Usuario");

        btnUsuarioInsertar.setBackground(new java.awt.Color(153, 153, 153));
        btnUsuarioInsertar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnUsuarioInsertar.setText("Insertar");

        btnUsuarioEditar.setBackground(new java.awt.Color(153, 153, 153));
        btnUsuarioEditar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnUsuarioEditar.setText("Editar");

        javax.swing.GroupLayout fondoUsuarioLayout = new javax.swing.GroupLayout(fondoUsuario);
        fondoUsuario.setLayout(fondoUsuarioLayout);
        fondoUsuarioLayout.setHorizontalGroup(
            fondoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(fondoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoUsuarioLayout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addGroup(fondoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUsuarioInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUsuarioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
        fondoUsuarioLayout.setVerticalGroup(
            fondoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(fondoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoUsuarioLayout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(3, 3, 3)
                    .addComponent(btnUsuarioInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(btnUsuarioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );

        fondoPermisos.add(fondoUsuario);
        fondoUsuario.setBounds(10, 195, 120, 120);

        fondoRoles.setBackground(new java.awt.Color(153, 153, 153));
        fondoRoles.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255)));

        btnRoles.setBackground(new java.awt.Color(153, 153, 153));
        btnRoles.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRoles.setText("Roles");

        btnRolesInsertar.setBackground(new java.awt.Color(153, 153, 153));
        btnRolesInsertar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRolesInsertar.setText("Insertar");

        btnRolesEditar.setBackground(new java.awt.Color(153, 153, 153));
        btnRolesEditar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRolesEditar.setText("Editar");

        javax.swing.GroupLayout fondoRolesLayout = new javax.swing.GroupLayout(fondoRoles);
        fondoRoles.setLayout(fondoRolesLayout);
        fondoRolesLayout.setHorizontalGroup(
            fondoRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(fondoRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoRolesLayout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addGroup(fondoRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRolesInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRolesEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
        fondoRolesLayout.setVerticalGroup(
            fondoRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(fondoRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoRolesLayout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(btnRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(3, 3, 3)
                    .addComponent(btnRolesInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(btnRolesEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );

        fondoPermisos.add(fondoRoles);
        fondoRoles.setBounds(135, 195, 120, 120);

        fondoGenero.setBackground(new java.awt.Color(153, 153, 153));
        fondoGenero.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255)));

        btnGenero.setBackground(new java.awt.Color(153, 153, 153));
        btnGenero.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnGenero.setText("Genero");

        btnGeneroInsertar.setBackground(new java.awt.Color(153, 153, 153));
        btnGeneroInsertar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnGeneroInsertar.setText("Insertar");

        btnGeneroEditar.setBackground(new java.awt.Color(153, 153, 153));
        btnGeneroEditar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnGeneroEditar.setText("Editar");

        javax.swing.GroupLayout fondoGeneroLayout = new javax.swing.GroupLayout(fondoGenero);
        fondoGenero.setLayout(fondoGeneroLayout);
        fondoGeneroLayout.setHorizontalGroup(
            fondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
            .addGroup(fondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoGeneroLayout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addGroup(fondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGeneroInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGeneroEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
        fondoGeneroLayout.setVerticalGroup(
            fondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(fondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoGeneroLayout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(btnGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(3, 3, 3)
                    .addComponent(btnGeneroInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(btnGeneroEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );

        fondoPermisos.add(fondoGenero);
        fondoGenero.setBounds(260, 195, 90, 120);

        fondoOrdenCompra.setBackground(new java.awt.Color(153, 153, 153));
        fondoOrdenCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255)));

        btnOrdenCompra.setBackground(new java.awt.Color(153, 153, 153));
        btnOrdenCompra.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnOrdenCompra.setText("Orden Compra");

        btnOrdenCompraInsertar.setBackground(new java.awt.Color(153, 153, 153));
        btnOrdenCompraInsertar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnOrdenCompraInsertar.setText("Insertar");

        btnOrdenCompraEditar.setBackground(new java.awt.Color(153, 153, 153));
        btnOrdenCompraEditar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnOrdenCompraEditar.setText("Editar");

        javax.swing.GroupLayout fondoOrdenCompraLayout = new javax.swing.GroupLayout(fondoOrdenCompra);
        fondoOrdenCompra.setLayout(fondoOrdenCompraLayout);
        fondoOrdenCompraLayout.setHorizontalGroup(
            fondoOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
            .addGroup(fondoOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoOrdenCompraLayout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addGroup(fondoOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOrdenCompraInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOrdenCompraEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        fondoOrdenCompraLayout.setVerticalGroup(
            fondoOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(fondoOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoOrdenCompraLayout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(btnOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(3, 3, 3)
                    .addComponent(btnOrdenCompraInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(btnOrdenCompraEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );

        fondoPermisos.add(fondoOrdenCompra);
        fondoOrdenCompra.setBounds(355, 195, 150, 120);

        jPanel1.add(fondoPermisos);
        fondoPermisos.setBounds(10, 140, 515, 330);

        foto.setBackground(new java.awt.Color(153, 153, 153));
        foto.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255)));
        jPanel1.add(foto);
        foto.setBounds(10, 10, 155, 130);

        btnEditar.setText("Edit");
        jPanel1.add(btnEditar);
        btnEditar.setBounds(540, 320, 70, 70);

        btnGuardar.setText("Guar");
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(540, 400, 70, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public RolUsuario obtenerElementos () {
        String rol = entRol.getText();
        Date fechaRegistro = entFechaRegistro.getDate();
        if (rol.isEmpty()) {
            caso = 1;
        }
        RolUsuario rolUsuario = new RolUsuario(rol, fechaRegistro);
        return rolUsuario;
    }
    
    public void obtenerElementoPermisos () {
        boolean cliente = btnCliente.isSelected();
        boolean empleado = btnEmpleado.isSelected();
        boolean usuario = btnUsuario.isSelected();
        boolean libro = btnLibro.isSelected();
        boolean ordenCompra = btnOrdenCompra.isSelected();
        boolean ordenPrestamo = btnOrdenPrestamo.isSelected();
        boolean roles = btnRoles.isSelected();
        boolean genero = btnGenero.isSelected();
        
        if  (cliente) {
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaRoles dialog = new ventanaRoles(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnCliente;
    private javax.swing.JRadioButton btnClienteEditar;
    private javax.swing.JRadioButton btnClienteInsertar;
    private javax.swing.JRadioButton btnClienteVer;
    private javax.swing.JButton btnEditar;
    private javax.swing.JRadioButton btnEmpleado;
    private javax.swing.JRadioButton btnEmpleadoEditar;
    private javax.swing.JRadioButton btnEmpleadoInsertar;
    private javax.swing.JRadioButton btnEmpleadoVer;
    private javax.swing.JRadioButton btnGenero;
    private javax.swing.JRadioButton btnGeneroEditar;
    private javax.swing.JRadioButton btnGeneroInsertar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JRadioButton btnLibro;
    private javax.swing.JRadioButton btnLibroEditar;
    private javax.swing.JRadioButton btnLibroInsertar;
    private javax.swing.JRadioButton btnLibroVer;
    private javax.swing.JRadioButton btnOrdenCompra;
    private javax.swing.JRadioButton btnOrdenCompraEditar;
    private javax.swing.JRadioButton btnOrdenCompraInsertar;
    private javax.swing.JRadioButton btnOrdenCompraVer;
    private javax.swing.JRadioButton btnOrdenPrestamo;
    private javax.swing.JRadioButton btnOrdenPrestamoEditar;
    private javax.swing.JRadioButton btnOrdenPrestamoInsertar;
    private javax.swing.JRadioButton btnRoles;
    private javax.swing.JRadioButton btnRolesEditar;
    private javax.swing.JRadioButton btnRolesInsertar;
    private javax.swing.JRadioButton btnUsuario;
    private javax.swing.JRadioButton btnUsuarioEditar;
    private javax.swing.JRadioButton btnUsuarioInsertar;
    private com.toedter.calendar.JDateChooser entFechaRegistro;
    private javax.swing.JTextField entRol;
    private javax.swing.JTextField entUsuario;
    private javax.swing.JPanel fondoCliente;
    private javax.swing.JPanel fondoEmpleado;
    private javax.swing.JPanel fondoGenero;
    private javax.swing.JPanel fondoLibro;
    private javax.swing.JPanel fondoOrdenCompra;
    private javax.swing.JPanel fondoOrdenPrestamo;
    private javax.swing.JPanel fondoPermisos;
    private javax.swing.JPanel fondoRoles;
    private javax.swing.JPanel fondoUsuario;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
