/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.Ordenprestamo;
import MODELO_CONTROLADOR.MC_OrdenPrestamo;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ayenni42
 */
public class ventanaVerOrdenPrestamo extends javax.swing.JDialog {

    /**
     * Creates new form ventanaVerOrdenPrestamo
     */
    private final String nombreTabla = "OrdenPrestamo";
    DefaultTableModel modelo;
    int numeroOrden;

    public ventanaVerOrdenPrestamo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        numeroOrden = 0;
        this.setSize(868, 564);
        modelo = (DefaultTableModel) tablaNumeroOrdenPrestamo.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNumeroOrdenPrestamo = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnVer = new javax.swing.JButton();
        btnVerTodo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        entNumeroOrden = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        tablaNumeroOrdenPrestamo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tablaNumeroOrdenPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Orden", "Numero Orden", "Nombre Empleado", "Nombre Cliente", "Fecha Entrega", "Estado Orden"
            }
        ));
        tablaNumeroOrdenPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaNumeroOrdenPrestamoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaNumeroOrdenPrestamo);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(5, 5, 736, 400);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(5, 100, 747, 410);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(5, 5, 830, 90);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        jPanel4.add(btnVer);
        btnVer.setBounds(5, 110, 70, 70);

        btnVerTodo.setText("Ver To");
        btnVerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodoActionPerformed(evt);
            }
        });
        jPanel4.add(btnVerTodo);
        btnVerTodo.setBounds(5, 335, 70, 70);

        btnEditar.setText("Edit");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditar);
        btnEditar.setBounds(5, 260, 70, 70);

        btnInsertar.setText("Insert");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel4.add(btnInsertar);
        btnInsertar.setBounds(5, 185, 70, 70);

        entNumeroOrden.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        entNumeroOrden.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entNumeroOrden.setText("# Orden");
        jPanel4.add(entNumeroOrden);
        entNumeroOrden.setBounds(5, 40, 70, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("# Orden");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(5, 5, 70, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(757, 100, 80, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiarTabla() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(modelo.getRowCount() - 1);
        }
    }

    private void tablaNumeroOrdenPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaNumeroOrdenPrestamoMouseClicked
        numeroOrden = Integer.parseInt(modelo.getValueAt(tablaNumeroOrdenPrestamo.getSelectedRow(), 1).toString());
        entNumeroOrden.setText(String.valueOf(numeroOrden));
    }//GEN-LAST:event_tablaNumeroOrdenPrestamoMouseClicked

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        if (numeroOrden > 0) {
            ventanaOrdenPrestamo ventanaOrdenP = new ventanaOrdenPrestamo(new javax.swing.JDialog(), true);
            MC_OrdenPrestamo controlOrdenP = new MC_OrdenPrestamo();
            Ordenprestamo ordenPrestamoAux = controlOrdenP.buscarOrdenPrestamo(numeroOrden);
            ventanaOrdenP.btnBuscarCliente.setVisible(false);
            ventanaOrdenP.btnBuscarEmpleado.setVisible(false);
            ventanaOrdenP.btnGuardar.setVisible(false);
            ventanaOrdenP.btnEditar.setVisible(false);
            ventanaOrdenP.setOrdenPrestamo(ordenPrestamoAux);
            ventanaOrdenP.mostrarElementos(ordenPrestamoAux);
            ventanaOrdenP.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No Ha Seleccionado Nada", "Informacion", 1, null);
        }
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnVerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodoActionPerformed
        limpiarTabla();
        numeroOrden = 0;
        entNumeroOrden.setText("# Orden");
        List<Ordenprestamo> OrdenPrestamo;
        MC_OrdenPrestamo controlOrdenP = new MC_OrdenPrestamo();
        OrdenPrestamo = controlOrdenP.buscarTodasOrdenesPrestamo();
        if (!OrdenPrestamo.isEmpty()) {
            for (Ordenprestamo ordenP : OrdenPrestamo) {
                int id = ordenP.getNumeroorden();
                SimpleDateFormat formato = new SimpleDateFormat("MM/dd/yyyy");
                String fechaOrden = "Sin Fecha";
                if (ordenP.getFechaorden() != null) {
                    fechaOrden = formato.format(ordenP.getFechaorden());
                }
                String nombreEmpleado = "Sin Nombre";
                if (ordenP.getEmpleadoId().getNombre() != null && !ordenP.getEmpleadoId().getNombre().isEmpty()) {
                    nombreEmpleado = ordenP.getEmpleadoId().getNombre();
                }
                String nombreCliente = "Sin Nombre ";
                if (ordenP.getClienteId().getNombre() != null && !ordenP.getClienteId().getNombre().isEmpty()) {
                    nombreCliente = ordenP.getClienteId().getNombre();
                }
                String fechaEntrega = "Sin Fecha Entrega";
                if (ordenP.getFechaentrega() != null) {
                    fechaEntrega = formato.format(ordenP.getFechaentrega());
                }
                String estadoOrden = "0";
                if (ordenP.getEstadoorden() != null && !ordenP.getEstadoorden().isEmpty()) {
                    estadoOrden = ordenP.getEstadoorden();
                }
                modelo.addRow(new Object[]{fechaOrden, id, nombreEmpleado, nombreCliente, fechaEntrega, estadoOrden});
            }
        } else {
            JOptionPane.showMessageDialog(this, "No Se Encontraron Ordenes De Prestamo", "Informacion", 1, null);
        }
    }//GEN-LAST:event_btnVerTodoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (numeroOrden > 0) {
            ventanaOrdenPrestamo ventanaOrdenP = new ventanaOrdenPrestamo(new javax.swing.JDialog(), true);
            limpiarTabla();
            MC_OrdenPrestamo controlOrdenP = new MC_OrdenPrestamo();
            Ordenprestamo ordenPrestamoAux = controlOrdenP.buscarOrdenPrestamo(numeroOrden);
            numeroOrden = 0;
            entNumeroOrden.setText("# Orden");
            ventanaOrdenP.btnGuardar.setVisible(false);
            ventanaOrdenP.setOrdenPrestamo(ordenPrestamoAux);
            ventanaOrdenP.mostrarElementos(ordenPrestamoAux);
            ventanaOrdenP.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No Ha Seleccionado Nada", "Informacion", 1, null);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        ventanaOrdenPrestamo ventanaOrdenP = new ventanaOrdenPrestamo(new javax.swing.JDialog(), true);
        ventanaOrdenP.btnEditar.setVisible(false);
        limpiarTabla();
        numeroOrden = 0;
        entNumeroOrden.setText("# Orden");
        ventanaOrdenP.numeroOrden();
        ventanaOrdenP.setVisible(true);
    }//GEN-LAST:event_btnInsertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaVerOrdenPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaVerOrdenPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaVerOrdenPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaVerOrdenPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaVerOrdenPrestamo dialog = new ventanaVerOrdenPrestamo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnVer;
    private javax.swing.JButton btnVerTodo;
    private javax.swing.JTextField entNumeroOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaNumeroOrdenPrestamo;
    // End of variables declaration//GEN-END:variables
}
