/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.Cliente;
import MODELO_CONTROLADOR.MC_Cliente;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ayenni42
 */
public class ventanaVerCliente extends javax.swing.JDialog {

    /**
     * Creates new form ventanaVerCliente
     */
    private final String nombreTabla = "Cliente";
    DefaultTableModel modelo;
    private int id;

    public ventanaVerCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        id = 0;
        this.setSize(867, 564);
        modelo = (DefaultTableModel) tablaCliente.getModel();
        entId.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnVer = new javax.swing.JButton();
        btnVerTodo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        entId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(900, 570));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        tablaCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Primer Nombre", "Apellido Paterno", "cedula", "telefono", "Fecha Registro"
            }
        ));
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCliente);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(5, 5, 736, 400);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(5, 100, 747, 410);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(5, 5, 830, 90);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        jPanel4.add(btnVer);
        btnVer.setBounds(5, 110, 70, 70);

        btnVerTodo.setText("Ver To");
        btnVerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodoActionPerformed(evt);
            }
        });
        jPanel4.add(btnVerTodo);
        btnVerTodo.setBounds(5, 335, 70, 70);

        btnEditar.setText("Edit");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditar);
        btnEditar.setBounds(5, 260, 70, 70);

        btnInsertar.setText("Insert");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel4.add(btnInsertar);
        btnInsertar.setBounds(5, 185, 70, 70);

        entId.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        entId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entId.setText("Id");
        jPanel4.add(entId);
        entId.setBounds(5, 75, 70, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Id Cliente");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(5, 40, 70, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(757, 100, 80, 410);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(5, 5, 842, 515);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiarTabla() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(modelo.getRowCount() - 1);
        }
    }
    private void btnVerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodoActionPerformed
        limpiarTabla();
        id = 0;
        entId.setText("Id");
        SimpleDateFormat formato = new SimpleDateFormat("MM/dd/yyy");
        List<Cliente> clientes;
        MC_Cliente controlCliente = new MC_Cliente();
        clientes = controlCliente.buscarTodosClientes();
        if (!clientes.isEmpty()) {
            for (Cliente cliente : clientes) {
                int id = cliente.getId();
                String primerNombre = "Sin Nombre";
                if (cliente.getNombre() != null && !cliente.getNombre().isEmpty()) {
                    primerNombre = cliente.getNombre();
                }
                String ApellidoMaterno = "Sin Apellido";
                if (cliente.getApellidoMaterno() != null && !cliente.getApellidoMaterno().isEmpty()) {
                    ApellidoMaterno = cliente.getApellidoMaterno();
                }
                String cedula = cliente.getCedula();
                String telefono = "Sin Telefono";
                if (cliente.getTelefono() != null && !cliente.getTelefono().isEmpty()) {
                    telefono = cliente.getTelefono();
                }
                String fecha = "Sin Fecha";
                if (cliente.getFechaRegistro() != null) {
                    fecha = formato.format(cliente.getFechaRegistro());
                }
                modelo.addRow(new Object[]{id, primerNombre, ApellidoMaterno, cedula, telefono, fecha});
            }
        } else {
            JOptionPane.showMessageDialog(this, "No Se Encontraron Clientes", "Informacion", 1, null);
        }
    }//GEN-LAST:event_btnVerTodoActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        if (id > 0) {
            ventanaCliente ventanaCli = new ventanaCliente(new javax.swing.JDialog(), true);
            MC_Cliente controlCliente = new MC_Cliente();
            Cliente clienteAux = controlCliente.buscarCliente(id);
            ventanaCli.btnGuargar.setVisible(false);
            ventanaCli.btnEditar.setVisible(false);
            ventanaCli.entFecha.setEnabled(false);
            ventanaCli.setCliente(clienteAux);
            ventanaCli.mostrarDatosVentana(clienteAux);
            ventanaCli.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No Ha Seleccionado Nada", "Informacion", 1, null);
        }
    }//GEN-LAST:event_btnVerActionPerformed

    private void tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseClicked
        id = Integer.parseInt(modelo.getValueAt(tablaCliente.getSelectedRow(), 0).toString());
        entId.setText(String.valueOf(id));
    }//GEN-LAST:event_tablaClienteMouseClicked

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        ventanaCliente ventanaCli = new ventanaCliente(new javax.swing.JDialog(), true);
        ventanaCli.btnEditar.setVisible(false);
        limpiarTabla();
        id = 0;
        entId.setText("Id");
        ventanaCli.setVisible(true);
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (id > 0) {
            ventanaCliente ventanaCli = new ventanaCliente(new javax.swing.JDialog(), true);
            limpiarTabla();
            MC_Cliente controlCliente = new MC_Cliente();
            Cliente clienteAux = controlCliente.buscarCliente(id);
            id = 0;
            entId.setText("Id");
            ventanaCli.btnGuargar.setVisible(false);
            ventanaCli.entFecha.setEnabled(false);
            ventanaCli.setCliente(clienteAux);
            ventanaCli.mostrarDatosVentana(clienteAux);
            ventanaCli.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No Ha Seleccionado Nada", "Informacion", 1, null);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaVerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaVerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaVerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaVerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaVerCliente dialog = new ventanaVerCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnVer;
    private javax.swing.JButton btnVerTodo;
    private javax.swing.JTextField entId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCliente;
    // End of variables declaration//GEN-END:variables
}
