/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.Genero;
import MODELO_CONTROLADOR.MC_Genero;
import MODELO_CONTROLADOR.funciones;
import com.toedter.calendar.JCalendar;
import javax.swing.JOptionPane;
import teclado.tecladoP;

/**
 *
 * @author ayenni42
 */
public class ventanaGenero extends javax.swing.JDialog {

    /**
     * Creates new form ventanaGenero
     */
    private Genero genero; 
    private tecladoP teclado = new tecladoP(this, true);

    public ventanaGenero(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        entId.setEditable(false);
        this.setSize(599,467);
        JCalendar calendario = entFechaCrecion.getJCalendar();
        calendario.setWeekOfYearVisible(false);
        calendario.setMaxDayCharacters(2);
        entFechaCrecion.setDate(funciones.fecha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        entId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        entFechaCrecion = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        entDescripcion = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnTeclado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Informacion Genero");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 290, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(54, 58, 60, 30);

        entNombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        entNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entNombreMouseClicked(evt);
            }
        });
        jPanel1.add(entNombre);
        entNombre.setBounds(119, 58, 400, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Id");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(450, 10, 20, 30);

        entId.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(entId);
        entId.setBounds(472, 10, 80, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Fecha Creacion");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 328, 120, 30);
        jPanel1.add(entFechaCrecion);
        entFechaCrecion.setBounds(145, 328, 130, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(310, 25, 135, 2);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Descripcion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 24))); // NOI18N
        jPanel2.setLayout(null);

        entDescripcion.setColumns(20);
        entDescripcion.setRows(5);
        entDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entDescripcionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(entDescripcion);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 512, 190);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 93, 532, 230);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/guardar65x65.png"))); // NOI18N
        btnGuardar.setMnemonic('G');
        btnGuardar.setToolTipText("Guardar Informacion Del Genero");
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setDefaultCapable(false);
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/guardar70x70.png"))); // NOI18N
        btnGuardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/guardar70x70.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(480, 330, 70, 70);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/editar65x65.png"))); // NOI18N
        btnEditar.setMnemonic('E');
        btnEditar.setToolTipText("Editar Informacion Del Genero");
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/editar70x70.png"))); // NOI18N
        btnEditar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/editar70x70.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar);
        btnEditar.setBounds(400, 330, 70, 70);

        btnTeclado.setText("Teclado");
        btnTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTecladoActionPerformed(evt);
            }
        });
        jPanel1.add(btnTeclado);
        btnTeclado.setBounds(320, 330, 70, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        genero = new Genero();
        obtenerElementos();

        if (JOptionPane.showConfirmDialog(this, "Guardar Genero", "Escudo", 1, 3, null) == 0) {
            MC_Genero control = new MC_Genero();
            if (control.nuevoGenero(genero)) {
                JOptionPane.showMessageDialog(this, "Genero Guardado", "Informacion", 1, null);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        obtenerElementos();
        
        if (JOptionPane.showConfirmDialog(this, "Editar Genero", "Escudo", 1, 3, null) == 0) {
            MC_Genero control = new MC_Genero();
            if (control.editarGenero(genero)) {
                JOptionPane.showMessageDialog(this, "Genero Editado", "Informacion", 1, null);
                this.setVisible(false);
            }
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void entNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entNombreMouseClicked
        teclado.setVisible(false);
        teclado.setArea(null);
        teclado.setCuadro(null);
        teclado.setCuadro(entNombre);
    }//GEN-LAST:event_entNombreMouseClicked

    private void entDescripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entDescripcionMouseClicked
        teclado.setVisible(false);
        teclado.setArea(null);
        teclado.setCuadro(null);
        teclado.setArea(entDescripcion);
    }//GEN-LAST:event_entDescripcionMouseClicked

    private void btnTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTecladoActionPerformed
        teclado.setVisible(true);
    }//GEN-LAST:event_btnTecladoActionPerformed

    public void obtenerElementos() {
        genero.setNombre(entNombre.getText());
        genero.setDescripcion(entDescripcion.getText());
        genero.setFechacreacion(entFechaCrecion.getDate());
    }

    public void mostrarElementos(Genero genero) {
        entId.setText(String.valueOf(genero.getId()));
        String nombre = "Sin Nombre";
        if (genero.getNombre() != null && !genero.getNombre().isEmpty()) {
            nombre = genero.getNombre();
        }
        String descripcion = "Sin Descripcion";
        if (genero.getDescripcion() != null && !genero.getDescripcion().isEmpty()) {
            descripcion = genero.getDescripcion();
        }
        entNombre.setText(nombre);
        entDescripcion.setText(descripcion);
        if (genero.getFechacreacion() != null) {
            entFechaCrecion.setDate(genero.getFechacreacion());
        }
    }

    public Genero getGenero() {
        return genero;
    }

    public void setGenero(Genero genero) {
        this.genero = genero;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaGenero dialog = new ventanaGenero(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnTeclado;
    private javax.swing.JTextArea entDescripcion;
    public com.toedter.calendar.JDateChooser entFechaCrecion;
    private javax.swing.JTextField entId;
    private javax.swing.JTextField entNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
