/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.Libro;
import MODELO.Permisos;
import MODELO_CONTROLADOR.MC_Libro;
import MODELO_CONTROLADOR.funciones;
import MODELO_CONTROLADOR.img_tabla;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ayenni42
 */
public class ventanaVerLibro extends javax.swing.JDialog {

    /**
     * Creates new form ventanaVerLibro
     */
    List<Libro> compraLibros = new ArrayList<>();
    private final String nombreTabla = "Libro";
    DefaultTableModel modelo;
    ventanaOrdenCompra ventana;
    ventanaOrdenPrestamo ventanaP;
    private int isbn;
    Permisos permiso;

    public ventanaVerLibro(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(868, 564);
        tablaLibro();
        isbn = 0;
    }

    public void tablaLibro() {
        tablaLibro.setDefaultRenderer(Object.class, new img_tabla());
        modelo = (DefaultTableModel) tablaLibro.getModel();
        tablaLibro.setRowHeight(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarLibro = new javax.swing.JPopupMenu();
        AgregarAlCarroDeCompra = new javax.swing.JMenuItem();
        FinalizarCompra = new javax.swing.JMenuItem();
        FinalizarPrestamo = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        entCarro = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibro = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnVer = new javax.swing.JButton();
        btnVerTodo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        entId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        AgregarAlCarroDeCompra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AgregarAlCarroDeCompra.setMnemonic('A');
        AgregarAlCarroDeCompra.setText("Agregar Al Carro");
        AgregarAlCarroDeCompra.setToolTipText("");
        AgregarAlCarroDeCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAlCarroDeCompraActionPerformed(evt);
            }
        });
        AgregarLibro.add(AgregarAlCarroDeCompra);

        FinalizarCompra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        FinalizarCompra.setMnemonic('F');
        FinalizarCompra.setText("Finalizar Compra");
        FinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompraActionPerformed(evt);
            }
        });
        AgregarLibro.add(FinalizarCompra);

        FinalizarPrestamo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        FinalizarPrestamo.setText("Finalizar Prestamo");
        FinalizarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarPrestamoActionPerformed(evt);
            }
        });
        AgregarLibro.add(FinalizarPrestamo);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(null);

        entCarro.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        entCarro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entCarro.setText("0");
        jPanel1.add(entCarro);
        entCarro.setBounds(760, 60, 70, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        tablaLibro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tablaLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "portada", "Isbn", "Titulo", "Autor", "Inventario", "Precio"
            }
        ));
        tablaLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaLibroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaLibro);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(5, 5, 736, 400);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(5, 100, 747, 410);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(5, 5, 747, 90);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        btnVer.setMnemonic('V');
        btnVer.setText("Ver");
        btnVer.setToolTipText("Ver Informacion Del libro");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        jPanel4.add(btnVer);
        btnVer.setBounds(5, 110, 70, 70);

        btnVerTodo.setMnemonic('T');
        btnVerTodo.setText("Ver To");
        btnVerTodo.setToolTipText("Ver Todos Los Libros");
        btnVerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodoActionPerformed(evt);
            }
        });
        jPanel4.add(btnVerTodo);
        btnVerTodo.setBounds(5, 335, 70, 70);

        btnEditar.setMnemonic('E');
        btnEditar.setText("Edit");
        btnEditar.setToolTipText("Editar Informacion Del Libro");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditar);
        btnEditar.setBounds(5, 260, 70, 70);

        btnInsertar.setMnemonic('I');
        btnInsertar.setText("Insert");
        btnInsertar.setToolTipText("Registrar Nuevo Libro");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel4.add(btnInsertar);
        btnInsertar.setBounds(5, 185, 70, 70);

        entId.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        entId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entId.setText("Isbn");
        jPanel4.add(entId);
        entId.setBounds(5, 30, 70, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Isbn Libro");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(5, 5, 70, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(757, 100, 80, 410);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Carro");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(760, 10, 65, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(5, 5, 842, 515);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiarTabla() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(modelo.getRowCount() - 1);
        }
    }

    private void tablaLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaLibroMouseClicked
        if (evt.isMetaDown()) {
            if (isbn > 0) {
                AgregarLibro.show(tablaLibro, evt.getX(), evt.getY());
            } else {
                JOptionPane.showMessageDialog(this, "No Se Ha Seleccionado Nada", "Advertencia", 2, null);
            }
        } else {
            isbn = Integer.parseInt(modelo.getValueAt(tablaLibro.getSelectedRow(), 1).toString());
            entId.setText(String.valueOf(isbn));
        }
    }//GEN-LAST:event_tablaLibroMouseClicked

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        if (isbn > 0) {
            ventanaLibro ventanaLibro = new ventanaLibro(new javax.swing.JDialog(), true);
            MC_Libro controlLibro = new MC_Libro();
            Libro libroAux = controlLibro.buscarLibro(isbn);
            ventanaLibro.btnGuardar.setVisible(false);
            ventanaLibro.btnEditar.setVisible(false);
            ventanaLibro.setLibro(libroAux);
            ventanaLibro.mostrarElementos(libroAux);
            ventanaLibro.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No  Ha Seleccionado Nada", "Informacion", 1, null);
        }
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnVerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodoActionPerformed
        limpiarTabla();
        isbn = 0;
        entId.setText("Isbn");
        List<Libro> libros;
        MC_Libro controlLibro = new MC_Libro();
        libros = controlLibro.buscarTodosLibros();
        if (!libros.isEmpty()) {
            for (Libro libro : libros) {
                int id = libro.getIsbn();
                ImageIcon Icon = new ImageIcon(getClass().getResource("/IMAGENES/fotoEmpleado.png"));
                ImageIcon portada = new ImageIcon(Icon.getImage().getScaledInstance(98, 98, Image.SCALE_DEFAULT));
                if (libro.getPortada() != null && libro.getPortada().length > 0) {
                    portada = new ImageIcon(funciones.byte_jpg(libro.getPortada()).getScaledInstance(98, 98, Image.SCALE_DEFAULT));
                }
                String titulo = "Sin Titulo";
                if (libro.getTitulo() != null && !libro.getTitulo().isEmpty()) {
                    titulo = libro.getTitulo();
                }
                String autor = "Sin Autor";
                if (libro.getAutor() != null && !libro.getAutor().isEmpty()) {
                    autor = libro.getAutor();
                }
                String inventario = "Sin Cantidad";
                if (libro.getEstadolibro() != null && !libro.getEstadolibro().isEmpty()) {
                    inventario = libro.getEstadolibro();
                }
                String precio = "0";
                if (libro.getPrecio() != null && libro.getPrecio() > 0) {
                    precio = String.valueOf(libro.getPrecio());
                }
                modelo.addRow(new Object[]{new JLabel(portada), id, titulo, autor, inventario, precio});
            }
        } else {
            JOptionPane.showMessageDialog(this, "No Se Encontraron Libros", "Informacion", 1, null);
        }
    }//GEN-LAST:event_btnVerTodoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (permiso != null && permiso.getIdpermisos() != null && permiso.getEditar()) {
            if (isbn > 0) {
                ventanaLibro ventanaLibro = new ventanaLibro(new javax.swing.JDialog(), true);
                limpiarTabla();
                MC_Libro controlLibro = new MC_Libro();
                Libro libroAux = controlLibro.buscarLibro(isbn);
                isbn = 0;
                entId.setText("Isbn");
                ventanaLibro.entIsbn.setEditable(false);
                ventanaLibro.btnGuardar.setVisible(false);
                ventanaLibro.setLibro(libroAux);
                ventanaLibro.mostrarElementos(libroAux);
                ventanaLibro.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No  Ha Seleccionado Nada", "Informacion", 1, null);
            }
        } else {
            JOptionPane.showMessageDialog(this, "EL Rol No Tiene Permiso Para Esta Opcion", "Error", 0, null);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        if (permiso != null && permiso.getIdpermisos() != null && permiso.getInsertar()) {
            ventanaLibro ventanaLibro = new ventanaLibro(new javax.swing.JDialog(), true);
            ventanaLibro.btnEditar.setVisible(false);
            limpiarTabla();
            isbn = 0;
            entId.setText("Isbn");
            ventanaLibro.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "EL Rol No Tiene Permiso Para Esta Opcion", "Error", 0, null);
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void AgregarAlCarroDeCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAlCarroDeCompraActionPerformed
        int cantidad = Integer.parseInt(entCarro.getText());
        String nombre = modelo.getValueAt(tablaLibro.getSelectedRow(), 2).toString();
        if (isbn > 0) {
            if (JOptionPane.showConfirmDialog(this, "Agregar Libro: " + nombre + " Al Carro De Compra.", "Escudo", 1, 3, null) == 0) {
                MC_Libro controlLibro = new MC_Libro();
                Libro seleccionLibro = controlLibro.buscarLibro(isbn);
                compraLibros.add(seleccionLibro);
                cantidad++;
                entCarro.setText(String.valueOf(cantidad));
            }
        }
    }//GEN-LAST:event_AgregarAlCarroDeCompraActionPerformed

    private void FinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompraActionPerformed
        boolean estado = true;
        if (ventana == null) {
            ventana = new ventanaOrdenCompra(new javax.swing.JDialog(), true);
            estado = false;
        }
        ventana.mostraLibro(compraLibros);
        ventana.btnAgregarLibro.setEnabled(false);
        ventana.btnEditar.setEnabled(false);
        ventana.numeroOrden();
        entCarro.setText("0");
        compraLibros = new ArrayList<>();
        if (estado) {
            this.setVisible(false);
        } else {
            ventana.setVisible(true);
        }
    }//GEN-LAST:event_FinalizarCompraActionPerformed

    private void FinalizarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarPrestamoActionPerformed
        boolean estado = true;
        if (ventanaP == null) {
            ventanaP = new ventanaOrdenPrestamo(new javax.swing.JDialog(), true);
            estado = false;
        }
        ventanaP.mostraLibro(compraLibros);
        ventanaP.btnAgregarLibro.setEnabled(false);
        ventanaP.btnEditar.setEnabled(false);
        ventanaP.numeroOrden();
        entCarro.setText("0");
        compraLibros = new ArrayList<>();
        if (estado) {
            this.setVisible(false);
        } else {
            ventanaP.setVisible(true);
        }
    }//GEN-LAST:event_FinalizarPrestamoActionPerformed

    public ventanaOrdenPrestamo getVentanaP() {
        return ventanaP;
    }

    public void setVentanaP(ventanaOrdenPrestamo ventanaP) {
        this.ventanaP = ventanaP;
    }

    public ventanaOrdenCompra getVentana() {
        return ventana;
    }

    public void setVentana(ventanaOrdenCompra ventana) {
        this.ventana = ventana;
    }

    public Permisos getPermiso() {
        return permiso;
    }

    public void setPermiso(Permisos permiso) {
        this.permiso = permiso;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaVerLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaVerLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaVerLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaVerLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaVerLibro dialog = new ventanaVerLibro(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarAlCarroDeCompra;
    private javax.swing.JPopupMenu AgregarLibro;
    private javax.swing.JMenuItem FinalizarCompra;
    private javax.swing.JMenuItem FinalizarPrestamo;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnInsertar;
    public javax.swing.JButton btnVer;
    public javax.swing.JButton btnVerTodo;
    private javax.swing.JTextField entCarro;
    private javax.swing.JTextField entId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaLibro;
    // End of variables declaration//GEN-END:variables
}
