/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.Cliente;
import MODELO.Empleado;
import MODELO.Libro;
import MODELO.Ordencompra;
import MODELO.Ordenprestamo;
import MODELO.Permisos;
import MODELO.RolUsuario;
import MODELO_CONTROLADOR.MC_Cliente;
import MODELO_CONTROLADOR.MC_Empleado;
import MODELO_CONTROLADOR.MC_Libro;
import MODELO_CONTROLADOR.MC_OrdenCompra;
import MODELO_CONTROLADOR.MC_OrdenPrestamo;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ayenni42
 */
public class ventanaMenu extends javax.swing.JDialog {

    /**
     * Creates new form ventanaMenu
     */
    RolUsuario rol = new RolUsuario();
    Permisos permiso = new Permisos();
    List<Permisos> permisosRol = new ArrayList<>();

    public ventanaMenu(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Libreria ¡Yo Si Compro Libros!");
        this.setSize(1015, 529);
        this.setMaximumSize(new Dimension(1015, 529));
        this.setMinimumSize(new Dimension(1015, 529));

        btnSesion.setComponentPopupMenu(MenuSesion);
        btnEmpleados.setComponentPopupMenu(menuEmpleados);
        btnClientes.setComponentPopupMenu(menuClientes);
        btnVentas.setComponentPopupMenu(menuVentas);
        btnRol.setComponentPopupMenu(menuRol);
        btnUsuario.setComponentPopupMenu(menuUsuario);
        btnGenero.setComponentPopupMenu(menuGenero);
        Desconectar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuSesion = new javax.swing.JPopupMenu();
        PerfilUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        InformacionEmpleado = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Desconectar = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        Conectar = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JPopupMenu();
        nuevoEmpleado = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        editarEmpleado = new javax.swing.JMenu();
        buscarIdEmpleado = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        buscarTodosEmpleados = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        verEmpleados = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JPopupMenu();
        nuevoCliente = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        editarCliente = new javax.swing.JMenu();
        buscarIdCliente = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        buscarTodosClientes = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        verClientes = new javax.swing.JMenuItem();
        menuLibros = new javax.swing.JPopupMenu();
        nuevoLibro = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        editarLibro = new javax.swing.JMenu();
        buscarIsbnLibro = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        buscarTodosLibros = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        verLibros = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JPopupMenu();
        Ventas = new javax.swing.JMenu();
        nuevaVenta = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        editarVentas = new javax.swing.JMenu();
        buscarNumeroVentas = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        buscarTodosVentas = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        verVentas = new javax.swing.JMenuItem();
        Prestamos = new javax.swing.JMenu();
        nuevoPrestamo = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        editarPrestamo = new javax.swing.JMenu();
        buscarNumeroPrestamo = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        buscarTodosPrestamos = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        verPrestamos = new javax.swing.JMenuItem();
        menuRol = new javax.swing.JPopupMenu();
        nuevoRol = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        editarRol = new javax.swing.JMenu();
        buscarNombreRol = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        buscarTodosRol = new javax.swing.JMenuItem();
        jSeparator21 = new javax.swing.JPopupMenu.Separator();
        verRol = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JPopupMenu();
        nuevoUsuario = new javax.swing.JMenuItem();
        jSeparator22 = new javax.swing.JPopupMenu.Separator();
        editarUsuario = new javax.swing.JMenu();
        buscarIdUsuario = new javax.swing.JMenuItem();
        jSeparator23 = new javax.swing.JPopupMenu.Separator();
        buscarTodosUsuarios = new javax.swing.JMenuItem();
        jSeparator24 = new javax.swing.JPopupMenu.Separator();
        verUsuarios = new javax.swing.JMenuItem();
        menuGenero = new javax.swing.JPopupMenu();
        nuevoGenero = new javax.swing.JMenuItem();
        jSeparator25 = new javax.swing.JPopupMenu.Separator();
        editarGenero = new javax.swing.JMenu();
        buscarIdGenero = new javax.swing.JMenuItem();
        jSeparator26 = new javax.swing.JPopupMenu.Separator();
        buscarTodosGeneros = new javax.swing.JMenuItem();
        jSeparator27 = new javax.swing.JPopupMenu.Separator();
        verGeneros = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        btnEmpleados = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnLibro = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnRol = new javax.swing.JButton();
        btnSesion = new javax.swing.JButton();
        fotoUsuario = new com.bolivia.label.CLabel();
        btnUsuario = new javax.swing.JButton();
        btnGenero = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();

        PerfilUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PerfilUsuario.setMnemonic('P');
        PerfilUsuario.setText("Perfil Usuario");
        PerfilUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilUsuarioActionPerformed(evt);
            }
        });
        MenuSesion.add(PerfilUsuario);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        MenuSesion.add(jSeparator1);

        InformacionEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        InformacionEmpleado.setMnemonic('I');
        InformacionEmpleado.setText("Informacion Empleado");
        MenuSesion.add(InformacionEmpleado);
        MenuSesion.add(jSeparator2);

        Desconectar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Desconectar.setMnemonic('D');
        Desconectar.setText("Desconectar");
        MenuSesion.add(Desconectar);
        MenuSesion.add(jSeparator13);

        Conectar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Conectar.setMnemonic('C');
        Conectar.setText("Conectar");
        Conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectarActionPerformed(evt);
            }
        });
        MenuSesion.add(Conectar);

        nuevoEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nuevoEmpleado.setMnemonic('N');
        nuevoEmpleado.setText("Nuevo Empleado");
        nuevoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoEmpleadoActionPerformed(evt);
            }
        });
        menuEmpleados.add(nuevoEmpleado);
        menuEmpleados.add(jSeparator3);

        editarEmpleado.setMnemonic('E');
        editarEmpleado.setText("Editar Empleados");

        buscarIdEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarIdEmpleado.setMnemonic('I');
        buscarIdEmpleado.setText("Buscar Empleado Por Id");
        buscarIdEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIdEmpleadoActionPerformed(evt);
            }
        });
        editarEmpleado.add(buscarIdEmpleado);
        editarEmpleado.add(jSeparator14);

        buscarTodosEmpleados.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarTodosEmpleados.setMnemonic('T');
        buscarTodosEmpleados.setText("Buscar Todos Los Empleados");
        buscarTodosEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTodosEmpleadosActionPerformed(evt);
            }
        });
        editarEmpleado.add(buscarTodosEmpleados);

        menuEmpleados.add(editarEmpleado);
        menuEmpleados.add(jSeparator4);

        verEmpleados.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        verEmpleados.setMnemonic('V');
        verEmpleados.setText("Ver Empleados");
        verEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEmpleadosActionPerformed(evt);
            }
        });
        menuEmpleados.add(verEmpleados);

        nuevoCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nuevoCliente.setMnemonic('N');
        nuevoCliente.setText("Nuevo Cliente");
        nuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoClienteActionPerformed(evt);
            }
        });
        menuClientes.add(nuevoCliente);
        menuClientes.add(jSeparator5);

        editarCliente.setMnemonic('E');
        editarCliente.setText("Editar Cliente");

        buscarIdCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarIdCliente.setMnemonic('I');
        buscarIdCliente.setText("Buscar Cliente Por Id ");
        buscarIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIdClienteActionPerformed(evt);
            }
        });
        editarCliente.add(buscarIdCliente);
        editarCliente.add(jSeparator15);

        buscarTodosClientes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarTodosClientes.setMnemonic('T');
        buscarTodosClientes.setText("Buscar Todos Los Clientes");
        buscarTodosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTodosClientesActionPerformed(evt);
            }
        });
        editarCliente.add(buscarTodosClientes);

        menuClientes.add(editarCliente);
        menuClientes.add(jSeparator6);

        verClientes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        verClientes.setMnemonic('V');
        verClientes.setText("Ver Todos Los Clientes");
        verClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verClientesActionPerformed(evt);
            }
        });
        menuClientes.add(verClientes);

        nuevoLibro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nuevoLibro.setMnemonic('N');
        nuevoLibro.setText("Nuevo Libro");
        nuevoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoLibroActionPerformed(evt);
            }
        });
        menuLibros.add(nuevoLibro);
        menuLibros.add(jSeparator11);

        editarLibro.setMnemonic('E');
        editarLibro.setText("Editar Libro");

        buscarIsbnLibro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarIsbnLibro.setMnemonic('I');
        buscarIsbnLibro.setText("Buscar Libro Por Id");
        buscarIsbnLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIsbnLibroActionPerformed(evt);
            }
        });
        editarLibro.add(buscarIsbnLibro);
        editarLibro.add(jSeparator18);

        buscarTodosLibros.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarTodosLibros.setMnemonic('T');
        buscarTodosLibros.setText("Buscar Todos Los Libros");
        buscarTodosLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTodosLibrosActionPerformed(evt);
            }
        });
        editarLibro.add(buscarTodosLibros);

        menuLibros.add(editarLibro);
        menuLibros.add(jSeparator12);

        verLibros.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        verLibros.setMnemonic('V');
        verLibros.setText("Ver Todos Los Libros");
        verLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verLibrosActionPerformed(evt);
            }
        });
        menuLibros.add(verLibros);

        Ventas.setMnemonic('V');
        Ventas.setText("Venta");
        Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasActionPerformed(evt);
            }
        });

        nuevaVenta.setMnemonic('N');
        nuevaVenta.setText("Nueva Venta");
        nuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaVentaActionPerformed(evt);
            }
        });
        Ventas.add(nuevaVenta);
        Ventas.add(jSeparator7);

        editarVentas.setMnemonic('E');
        editarVentas.setText("Editar Libro");

        buscarNumeroVentas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarNumeroVentas.setMnemonic('N');
        buscarNumeroVentas.setText("Bucar Libro Por Id");
        buscarNumeroVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNumeroVentasActionPerformed(evt);
            }
        });
        editarVentas.add(buscarNumeroVentas);
        editarVentas.add(jSeparator16);

        buscarTodosVentas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarTodosVentas.setMnemonic('T');
        buscarTodosVentas.setText("Buscar Todos Los Libros");
        buscarTodosVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTodosVentasActionPerformed(evt);
            }
        });
        editarVentas.add(buscarTodosVentas);

        Ventas.add(editarVentas);
        Ventas.add(jSeparator8);

        verVentas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        verVentas.setMnemonic('V');
        verVentas.setText("Ver Todas Las Ventas");
        verVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verVentasActionPerformed(evt);
            }
        });
        Ventas.add(verVentas);

        menuVentas.add(Ventas);

        Prestamos.setMnemonic('P');
        Prestamos.setText("Prestamo");
        Prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrestamosActionPerformed(evt);
            }
        });

        nuevoPrestamo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nuevoPrestamo.setMnemonic('N');
        nuevoPrestamo.setText("Nuevo Prestamo");
        nuevoPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoPrestamoActionPerformed(evt);
            }
        });
        Prestamos.add(nuevoPrestamo);
        Prestamos.add(jSeparator9);

        editarPrestamo.setMnemonic('E');
        editarPrestamo.setText("Editar Prestamo");

        buscarNumeroPrestamo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarNumeroPrestamo.setMnemonic('N');
        buscarNumeroPrestamo.setText("Buscar Prestamo Por Id");
        buscarNumeroPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNumeroPrestamoActionPerformed(evt);
            }
        });
        editarPrestamo.add(buscarNumeroPrestamo);
        editarPrestamo.add(jSeparator17);

        buscarTodosPrestamos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarTodosPrestamos.setMnemonic('T');
        buscarTodosPrestamos.setText("Buscar Todos Los Prestamo");
        buscarTodosPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTodosPrestamosActionPerformed(evt);
            }
        });
        editarPrestamo.add(buscarTodosPrestamos);

        Prestamos.add(editarPrestamo);
        Prestamos.add(jSeparator10);

        verPrestamos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        verPrestamos.setMnemonic('V');
        verPrestamos.setText("Ver Todos Los Prestamos");
        verPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPrestamosActionPerformed(evt);
            }
        });
        Prestamos.add(verPrestamos);

        menuVentas.add(Prestamos);

        nuevoRol.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nuevoRol.setMnemonic('N');
        nuevoRol.setText("Nuevo Rol");
        nuevoRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoRolActionPerformed(evt);
            }
        });
        menuRol.add(nuevoRol);
        menuRol.add(jSeparator19);

        editarRol.setMnemonic('E');
        editarRol.setText("Editar Rol");

        buscarNombreRol.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarNombreRol.setMnemonic('N');
        buscarNombreRol.setText("Buscar Rol Por usuario");
        editarRol.add(buscarNombreRol);
        editarRol.add(jSeparator20);

        buscarTodosRol.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarTodosRol.setMnemonic('T');
        buscarTodosRol.setText("Buscar Todos Los Rol ");
        buscarTodosRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTodosRolActionPerformed(evt);
            }
        });
        editarRol.add(buscarTodosRol);

        menuRol.add(editarRol);
        menuRol.add(jSeparator21);

        verRol.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        verRol.setMnemonic('V');
        verRol.setText("Ver Rol");
        verRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verRolActionPerformed(evt);
            }
        });
        menuRol.add(verRol);

        nuevoUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nuevoUsuario.setMnemonic('N');
        nuevoUsuario.setText("Nuevo Usuario");
        nuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(nuevoUsuario);
        menuUsuario.add(jSeparator22);

        editarUsuario.setMnemonic('E');
        editarUsuario.setText("Editar Empleados");

        buscarIdUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarIdUsuario.setMnemonic('I');
        buscarIdUsuario.setText("Buscar Usuario Por Id");
        editarUsuario.add(buscarIdUsuario);
        editarUsuario.add(jSeparator23);

        buscarTodosUsuarios.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarTodosUsuarios.setMnemonic('T');
        buscarTodosUsuarios.setText("Buscar Todos Los Usuario");
        buscarTodosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTodosUsuariosActionPerformed(evt);
            }
        });
        editarUsuario.add(buscarTodosUsuarios);

        menuUsuario.add(editarUsuario);
        menuUsuario.add(jSeparator24);

        verUsuarios.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        verUsuarios.setMnemonic('V');
        verUsuarios.setText("Ver Usuarios");
        verUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verUsuariosActionPerformed(evt);
            }
        });
        menuUsuario.add(verUsuarios);

        nuevoGenero.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nuevoGenero.setMnemonic('N');
        nuevoGenero.setText("Nuevo Genero");
        nuevoGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoGeneroActionPerformed(evt);
            }
        });
        menuGenero.add(nuevoGenero);
        menuGenero.add(jSeparator25);

        editarGenero.setMnemonic('E');
        editarGenero.setText("Editar Genero");

        buscarIdGenero.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarIdGenero.setMnemonic('I');
        buscarIdGenero.setText("Buscar Genero Por Id");
        editarGenero.add(buscarIdGenero);
        editarGenero.add(jSeparator26);

        buscarTodosGeneros.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarTodosGeneros.setMnemonic('T');
        buscarTodosGeneros.setText("Buscar Todos Los Generos");
        buscarTodosGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTodosGenerosActionPerformed(evt);
            }
        });
        editarGenero.add(buscarTodosGeneros);

        menuGenero.add(editarGenero);
        menuGenero.add(jSeparator27);

        verGeneros.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        verGeneros.setMnemonic('V');
        verGeneros.setText("Ver Generos");
        verGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verGenerosActionPerformed(evt);
            }
        });
        menuGenero.add(verGeneros);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(null);

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menu.setLayout(null);

        btnEmpleados.setBackground(new java.awt.Color(204, 204, 204));
        btnEmpleados.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEmpleados.setMnemonic('E');
        btnEmpleados.setText("Empleado ");
        btnEmpleados.setToolTipText("Informacion De Los Empleados");
        btnEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEmpleados.setContentAreaFilled(false);
        btnEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        menu.add(btnEmpleados);
        btnEmpleados.setBounds(5, 2, 120, 36);

        btnClientes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnClientes.setMnemonic('C');
        btnClientes.setText("Cliente ");
        btnClientes.setToolTipText("Informacion De Los Clientes");
        btnClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClientes.setContentAreaFilled(false);
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        menu.add(btnClientes);
        btnClientes.setBounds(130, 2, 120, 36);

        btnLibro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLibro.setMnemonic('L');
        btnLibro.setText("Libro ");
        btnLibro.setToolTipText("Informacion De Libros");
        btnLibro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLibro.setContentAreaFilled(false);
        btnLibro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnLibro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibroActionPerformed(evt);
            }
        });
        menu.add(btnLibro);
        btnLibro.setBounds(255, 2, 120, 36);

        btnVentas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnVentas.setMnemonic('V');
        btnVentas.setText("Venta-Prestamos ");
        btnVentas.setToolTipText("Informacion De Las Ventas");
        btnVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVentas.setContentAreaFilled(false);
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        menu.add(btnVentas);
        btnVentas.setBounds(380, 2, 120, 36);

        btnRol.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnRol.setMnemonic('R');
        btnRol.setText("Rol ");
        btnRol.setToolTipText("Informacion Del Rol");
        btnRol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRol.setContentAreaFilled(false);
        btnRol.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnRol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRolActionPerformed(evt);
            }
        });
        menu.add(btnRol);
        btnRol.setBounds(505, 2, 120, 36);

        btnSesion.setMnemonic('S');
        btnSesion.setToolTipText("Informacion De Cuenta De Usuario");
        btnSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSesion.setContentAreaFilled(false);
        btnSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesionActionPerformed(evt);
            }
        });
        menu.add(btnSesion);
        btnSesion.setBounds(960, 10, 20, 20);

        fotoUsuario.setText("");
        fotoUsuario.setToolTipText("Foto Usuario");
        menu.add(fotoUsuario);
        fotoUsuario.setBounds(920, 2, 36, 36);

        btnUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnUsuario.setMnemonic('U');
        btnUsuario.setText("Usuario ");
        btnUsuario.setToolTipText("Informacion De Usuario");
        btnUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUsuario.setContentAreaFilled(false);
        btnUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        menu.add(btnUsuario);
        btnUsuario.setBounds(630, 2, 120, 36);

        btnGenero.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnGenero.setMnemonic('G');
        btnGenero.setText("Genero ");
        btnGenero.setToolTipText("Informacion De Genero");
        btnGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGenero.setContentAreaFilled(false);
        btnGenero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnGenero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneroActionPerformed(evt);
            }
        });
        menu.add(btnGenero);
        btnGenero.setBounds(755, 2, 120, 36);

        jPanel1.add(menu);
        menu.setBounds(2, 2, 986, 40);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Grafica Ventas Empleado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(200, 260, 787, 214);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Libros Vendidos Reciente Mente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Isbn", "Titulo", "Autor", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(5, 20, 777, 188);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(200, 44, 787, 214);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setOpaque(false);
        jPanel1.add(jPanel4);
        jPanel4.setBounds(3, 44, 194, 432);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(5, 5, 990, 480);
        jPanel1.getAccessibleContext().setAccessibleName("Libreria ¡Yo Si Compro Libros!");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Permisos buscarPermiso(String nombreTabla) {
        Permisos per = new Permisos();
        for (Permisos permiso : permisosRol) {
            if (nombreTabla.equals(permiso.getNombreTabla())) {
                per = permiso;
                break;
            }
        }
        return per;
    }
    private void PerfilUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilUsuarioActionPerformed
        System.out.println("tamaño: " + this.getSize());
    }//GEN-LAST:event_PerfilUsuarioActionPerformed

    private void nuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoEmpleadoActionPerformed
        ventanaEmpleado ventana = new ventanaEmpleado(new javax.swing.JDialog(), true);
        ventana.btnEditar.setEnabled(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_nuevoEmpleadoActionPerformed

    private void verEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEmpleadosActionPerformed
        ventanaVerEmpleado ventana = new ventanaVerEmpleado(new javax.swing.JDialog(), true);
        ventana.setPermiso(permiso);
        ventana.setVisible(true);
    }//GEN-LAST:event_verEmpleadosActionPerformed

    private void buscarIdEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIdEmpleadoActionPerformed
        ventanaEmpleado ventana = new ventanaEmpleado(new javax.swing.JDialog(), true);
        String idEmpleado = JOptionPane.showInputDialog(this, "Porfavor Ingrese El Id Del Empleado", "Buscar Empleado Por Id", 3);
        if (idEmpleado != null && !idEmpleado.isEmpty()) {
            int id = Integer.parseInt(idEmpleado);
            MC_Empleado controlEmpleado = new MC_Empleado();
            Empleado empleado = controlEmpleado.buscarEmpleado(id);
            if (empleado.getId() != null && empleado.getId() > 0) {
                ventana.btnGuardar.setEnabled(false);
                ventana.entFechaContrato.setEnabled(false);
                ventana.setEmpleado(empleado);
                ventana.mostrarElementos(empleado);
                ventana.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No Se Encontro El Empleado", "Informacion", 1, null);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Parametro Invalido", "Error", 0, null);
        }
    }//GEN-LAST:event_buscarIdEmpleadoActionPerformed

    private void buscarTodosEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTodosEmpleadosActionPerformed
        verEmpleadosActionPerformed(evt);
    }//GEN-LAST:event_buscarTodosEmpleadosActionPerformed

    private void nuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoClienteActionPerformed
        ventanaCliente ventana = new ventanaCliente(new javax.swing.JDialog(), true);
        ventana.btnMensaje.setEnabled(false);
        ventana.btnEditar.setEnabled(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_nuevoClienteActionPerformed

    private void verClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verClientesActionPerformed
        ventanaVerCliente ventana = new ventanaVerCliente(new javax.swing.JDialog(), true);
        ventana.setPermiso(permiso);
        ventana.setVisible(true);
    }//GEN-LAST:event_verClientesActionPerformed

    private void buscarIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIdClienteActionPerformed
        ventanaCliente ventana = new ventanaCliente(new javax.swing.JDialog(), true);
        String idCliente = JOptionPane.showInputDialog(this, "Porfavor Ingrese El Id Del Cliente", "Buscar Cliente Por Id", 3);
        if (idCliente != null && !idCliente.isEmpty()) {
            int id = Integer.parseInt(idCliente);
            MC_Cliente controlCliente = new MC_Cliente();
            Cliente cliente = controlCliente.buscarCliente(id);
            if (cliente.getId() != null && cliente.getId() > 0) {
                ventana.btnMensaje.setEnabled(false);
                ventana.entCedula.setEditable(false);
                ventana.btnGuargar.setEnabled(false);
                ventana.entFecha.setEnabled(false);
                ventana.setCliente(cliente);
                ventana.mostrarDatosVentana(cliente);
                ventana.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No Se Encontro El Cliente", "Informacion", 1, null);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Parametro Invalido", "Error", 0, null);
        }
    }//GEN-LAST:event_buscarIdClienteActionPerformed

    private void buscarTodosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTodosClientesActionPerformed
        ventanaVerCliente ventana = new ventanaVerCliente(new javax.swing.JDialog(), true);
        ventana.setPermiso(permiso);
        ventana.btnInsertar.setEnabled(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_buscarTodosClientesActionPerformed

    private void nuevoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoLibroActionPerformed
        ventanaLibro ventana = new ventanaLibro(new javax.swing.JDialog(), true);
        ventana.btnEditar.setEnabled(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_nuevoLibroActionPerformed

    private void verLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verLibrosActionPerformed
        ventanaVerLibro ventana = new ventanaVerLibro(new javax.swing.JDialog(), true);
        ventana.setPermiso(permiso);
        ventana.setVisible(true);
    }//GEN-LAST:event_verLibrosActionPerformed

    private void buscarIsbnLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIsbnLibroActionPerformed
        ventanaLibro ventana = new ventanaLibro(new javax.swing.JDialog(), true);
        String isbnLibro = JOptionPane.showInputDialog(this, "Porfavor Ingrese El Isbn Del Libro", "Buscar Libro Por Isbn", 3);
        if (isbnLibro != null && !isbnLibro.isEmpty()) {
            int id = Integer.parseInt(isbnLibro);
            MC_Libro controlLibro = new MC_Libro();
            Libro libro = controlLibro.buscarLibro(id);
            if (libro.getIsbn() != null && libro.getIsbn() > 0) {
                ventana.btnGuardar.setEnabled(false);
                ventana.btnBuscar.setEnabled(false);
                ventana.setLibro(libro);
                ventana.mostrarElementos(libro);
                ventana.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No Se Encontro El Libro", "Informacion", 1, null);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Parametro Invalido", "Error", 0, null);
        }
    }//GEN-LAST:event_buscarIsbnLibroActionPerformed

    private void buscarTodosLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTodosLibrosActionPerformed
        ventanaVerLibro ventana = new ventanaVerLibro(new javax.swing.JDialog(), true);
        ventana.setPermiso(permiso);
        ventana.btnInsertar.setEnabled(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_buscarTodosLibrosActionPerformed

    private void nuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaVentaActionPerformed
        ventanaOrdenCompra ventana = new ventanaOrdenCompra(new javax.swing.JDialog(), true);
        ventana.btnEditar.setEnabled(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_nuevaVentaActionPerformed

    private void verVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verVentasActionPerformed
        ventanaVerOrdenCompra ventana = new ventanaVerOrdenCompra(new javax.swing.JDialog(), true);
        ventana.setPermiso(permiso);
        ventana.setVisible(true);
    }//GEN-LAST:event_verVentasActionPerformed

    private void buscarNumeroVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNumeroVentasActionPerformed
        ventanaOrdenCompra ventana = new ventanaOrdenCompra(new javax.swing.JDialog(), true);
        String numeroOrden = JOptionPane.showInputDialog(this, "Porfavor Ingrese El Numero De La Orden", "Buscar Orden Por Numero", 3);
        if (numeroOrden != null && !numeroOrden.isEmpty()) {
            int id = Integer.parseInt(numeroOrden);
            MC_OrdenCompra controlOrden = new MC_OrdenCompra();
            Ordencompra ordenCompra = controlOrden.buscarOrdenCompra(id);
            if (ordenCompra.getNumeroorden() != null && ordenCompra.getNumeroorden() > 0) {
                ventana.btnGuardar.setEnabled(false);
                ventana.btnAgregarLibro.setEnabled(false);
                ventana.btnCancelar.setEnabled(false);
                ventana.setOrdenCompra(ordenCompra);
                ventana.mostrarElementosOrdenCompra(ordenCompra);
                ventana.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No Se Encontro Orden De Compra", "Informacion", 1, null);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Parametro Invalido", "Error", 0, null);
        }
    }//GEN-LAST:event_buscarNumeroVentasActionPerformed

    private void buscarTodosVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTodosVentasActionPerformed
        ventanaVerOrdenCompra ventana = new ventanaVerOrdenCompra(new javax.swing.JDialog(), true);
        ventana.setPermiso(permiso);
        ventana.btnInsertar.setEnabled(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_buscarTodosVentasActionPerformed

    private void nuevoPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoPrestamoActionPerformed
        ventanaOrdenPrestamo ventana = new ventanaOrdenPrestamo(new javax.swing.JDialog(), true);
        ventana.btnEditar.setEnabled(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_nuevoPrestamoActionPerformed

    private void buscarNumeroPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNumeroPrestamoActionPerformed
        ventanaOrdenPrestamo ventana = new ventanaOrdenPrestamo(new javax.swing.JDialog(), true);
        String numeroOrden = JOptionPane.showInputDialog(this, "Porfavor Ingrese El Numero De La Orden", "Buscar Orden Por Numero", 3);
        if (numeroOrden != null && !numeroOrden.isEmpty()) {
            int id = Integer.parseInt(numeroOrden);
            MC_OrdenPrestamo controlOrden = new MC_OrdenPrestamo();
            Ordenprestamo ordenPrestamo = controlOrden.buscarOrdenPrestamo(id);
            if (ordenPrestamo.getNumeroorden() != null && ordenPrestamo.getNumeroorden() > 0) {
                ventana.btnGuardar.setEnabled(false);
                ventana.btnAgregarLibro.setEnabled(false);
                ventana.btnCancelar.setEnabled(false);
                ventana.setOrdenPrestamo(ordenPrestamo);
                ventana.mostrarElementos(ordenPrestamo);
                ventana.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No Se Encontro Orden De Prestamo", "Informacion", 1, null);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Parametro Invalido", "Error", 0, null);
        }
    }//GEN-LAST:event_buscarNumeroPrestamoActionPerformed

    private void buscarTodosPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTodosPrestamosActionPerformed
        ventanaVerOrdenPrestamo ventana = new ventanaVerOrdenPrestamo(new javax.swing.JDialog(),true);
        ventana.btnInsertar.setEnabled(false);
        ventana.setPermiso(permiso);
        ventana.setVisible(true);
    }//GEN-LAST:event_buscarTodosPrestamosActionPerformed

    private void verPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPrestamosActionPerformed
        ventanaVerOrdenPrestamo ventana = new ventanaVerOrdenPrestamo(new javax.swing.JDialog(),true);
        ventana.setPermiso(permiso);
        ventana.setVisible(true);
    }//GEN-LAST:event_verPrestamosActionPerformed

    private void ConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectarActionPerformed
        ventanaLogin ventana = new ventanaLogin(new javax.swing.JDialog(), true);
        ventana.setVentana(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_ConectarActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        permiso = buscarPermiso("Empleado");
        if (permiso.getIdpermisos() != null) {
            nuevoEmpleado.setEnabled(permiso.getInsertar());
            editarEmpleado.setEnabled(permiso.getEditar());
            verEmpleados.setEnabled(permiso.getVer());
            buscarTodosEmpleados.setEnabled(permiso.getVer());
        } else {
            nuevoEmpleado.setEnabled(false);
            editarEmpleado.setEnabled(false);
            verEmpleados.setEnabled(false);
            buscarTodosEmpleados.setEnabled(false);
        }
        menuEmpleados.show(btnEmpleados, 1, 34);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        permiso = buscarPermiso("Cliente");
        if (permiso.getIdpermisos() != null) {
            nuevoCliente.setEnabled(permiso.getInsertar());
            editarCliente.setEnabled(permiso.getEditar());
            verClientes.setEnabled(permiso.getVer());
            buscarTodosClientes.setEnabled(permiso.getVer());
        } else {
            nuevoCliente.setEnabled(false);
            editarCliente.setEnabled(false);
            verClientes.setEnabled(false);
            buscarTodosClientes.setEnabled(false);

        }
        menuClientes.show(btnClientes, 1, 34);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibroActionPerformed
        permiso = buscarPermiso("Libro");
        if (permiso.getIdpermisos() != null) {
            nuevoLibro.setEnabled(permiso.getInsertar());
            editarLibro.setEnabled(permiso.getEditar());
            verLibros.setEnabled(permiso.getVer());
            buscarTodosLibros.setEnabled(permiso.getVer());
        } else {
            nuevoLibro.setEnabled(false);
            editarLibro.setEnabled(false);
            verLibros.setEnabled(false);
            buscarTodosLibros.setEnabled(false);

        }
        menuLibros.show(btnLibro, 1, 34);
    }//GEN-LAST:event_btnLibroActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        permiso = buscarPermiso("OrdenCompra");
        if (permiso.getIdpermisos() != null) {
            nuevaVenta.setEnabled(permiso.getInsertar());
            editarVentas.setEnabled(permiso.getEditar());
            verVentas.setEnabled(permiso.getVer());
            buscarTodosVentas.setEnabled(permiso.getVer());
        } else {
            nuevaVenta.setEnabled(false);
            editarVentas.setEnabled(false);
            verVentas.setEnabled(false);
            buscarTodosVentas.setEnabled(false);
        }
        Permisos permisoP = buscarPermiso("OrdenPrestamo");
        if (permisoP.getIdpermisos() != null) {
            nuevoPrestamo.setEnabled(permisoP.getInsertar());
            editarPrestamo.setEnabled(permisoP.getEditar());
            verPrestamos.setEnabled(permisoP.getVer());
            buscarTodosPrestamos.setEnabled(permisoP.getVer());
        } else {
            nuevoPrestamo.setEnabled(false);
            editarPrestamo.setEnabled(false);
            verPrestamos.setEnabled(false);
            buscarTodosPrestamos.setEnabled(false);
        }
        menuVentas.show(btnVentas, 1, 34);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolActionPerformed
        permiso = buscarPermiso("Rol");
        if (permiso.getIdpermisos() != null) {
            nuevoRol.setEnabled(permiso.getInsertar());
            editarRol.setEnabled(permiso.getEditar());
            verRol.setEnabled(permiso.getVer());
            buscarTodosRol.setEnabled(permiso.getVer());
        } else {
            nuevoRol.setEnabled(false);
            editarRol.setEnabled(false);
            verRol.setEnabled(false);
            buscarTodosRol.setEnabled(false);
        }
        menuRol.show(btnRol, 1, 34);
    }//GEN-LAST:event_btnRolActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        permiso = buscarPermiso("Usuario");
        if (permiso.getIdpermisos() != null) {
            nuevoUsuario.setEnabled(permiso.getInsertar());
            editarUsuario.setEnabled(permiso.getEditar());
            verUsuarios.setEnabled(permiso.getVer());
            buscarTodosUsuarios.setEnabled(permiso.getVer());
        } else {
            nuevoUsuario.setEnabled(false);
            editarUsuario.setEnabled(false);
            verUsuarios.setEnabled(false);
            buscarTodosUsuarios.setEnabled(false);
        }
        menuUsuario.show(btnUsuario, 1, 34);
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneroActionPerformed
        permiso = buscarPermiso("Genero");
        if (permiso.getIdpermisos() != null) {
            nuevoGenero.setEnabled(permiso.getInsertar());
            editarGenero.setEnabled(permiso.getEditar());
            verGeneros.setEnabled(permiso.getVer());
            buscarTodosGeneros.setEnabled(permiso.getVer());
        } else {
            nuevoGenero.setEnabled(false);
            editarGenero.setEnabled(false);
            verGeneros.setEnabled(false);
            buscarTodosGeneros.setEnabled(false);
        }
        menuGenero.show(btnGenero, 1, 34);
    }//GEN-LAST:event_btnGeneroActionPerformed

    private void VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasActionPerformed
        permiso = buscarPermiso("OrdenCompra");
    }//GEN-LAST:event_VentasActionPerformed

    private void PrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrestamosActionPerformed
        permiso = buscarPermiso("OrdenPrestamo");
    }//GEN-LAST:event_PrestamosActionPerformed

    private void btnSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesionActionPerformed
        MenuSesion.show(btnSesion, 1, 20);
    }//GEN-LAST:event_btnSesionActionPerformed

    private void verRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verRolActionPerformed
        ventanaVerRolUsuario ventana = new ventanaVerRolUsuario(new javax.swing.JDialog(), true);
        ventana.setPermiso(permiso);
        ventana.setVisible(true);
    }//GEN-LAST:event_verRolActionPerformed

    private void nuevoRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoRolActionPerformed
        ventanaRoles ventana = new ventanaRoles (new javax.swing.JDialog(),true);
        ventana.btnEditar.setEnabled(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_nuevoRolActionPerformed

    private void buscarTodosRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTodosRolActionPerformed
        ventanaVerRolUsuario ventana = new ventanaVerRolUsuario(new javax.swing.JDialog(), true);
        ventana.setPermiso(permiso);
        ventana.btnInsertar.setEnabled(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_buscarTodosRolActionPerformed

    private void nuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoUsuarioActionPerformed
        ventanaUsuario ventana = new ventanaUsuario(new javax.swing.JDialog(), true);
        ventana.btnEditar.setEnabled(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_nuevoUsuarioActionPerformed

    private void buscarTodosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTodosUsuariosActionPerformed
        ventanaVerUsuario ventana = new ventanaVerUsuario(new javax.swing.JDialog(), true);
        ventana.setPermiso(permiso);
        ventana.btnInsertar.setEnabled(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_buscarTodosUsuariosActionPerformed

    private void verUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verUsuariosActionPerformed
        ventanaVerUsuario ventana = new ventanaVerUsuario(new javax.swing.JDialog(), true);
        ventana.setPermiso(permiso);
        ventana.setVisible(true);
    }//GEN-LAST:event_verUsuariosActionPerformed

    private void nuevoGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoGeneroActionPerformed
        ventanaGenero ventana = new ventanaGenero(new javax.swing.JDialog(), true);
        ventana.btnEditar.setEnabled(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_nuevoGeneroActionPerformed

    private void buscarTodosGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTodosGenerosActionPerformed
        ventanaverGenero ventana = new ventanaverGenero(new javax.swing.JDialog(), true);
        ventana.btnAgregar.setEnabled(false);
        ventana.btnInsertar.setEnabled(false);
        ventana.setPermiso(permiso);
        ventana.setVisible(true);
    }//GEN-LAST:event_buscarTodosGenerosActionPerformed

    private void verGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verGenerosActionPerformed
        ventanaverGenero ventana = new ventanaverGenero(new javax.swing.JDialog(), true);
        ventana.btnAgregar.setEnabled(false);
        ventana.setPermiso(permiso);
        ventana.setVisible(true);
    }//GEN-LAST:event_verGenerosActionPerformed

    public RolUsuario getRol() {
        return rol;
    }

    public void setRol(RolUsuario rol) {
        this.rol = rol;
    }

    public List<Permisos> getPermisosRol() {
        return permisosRol;
    }

    public void setPermisosRol(List<Permisos> permisosRol) {
        this.permisosRol = permisosRol;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaMenu dialog = new ventanaMenu(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem Conectar;
    public javax.swing.JMenuItem Desconectar;
    private javax.swing.JMenuItem InformacionEmpleado;
    private javax.swing.JPopupMenu MenuSesion;
    public javax.swing.JMenuItem PerfilUsuario;
    private javax.swing.JMenu Prestamos;
    private javax.swing.JMenu Ventas;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnGenero;
    private javax.swing.JButton btnLibro;
    private javax.swing.JButton btnRol;
    private javax.swing.JButton btnSesion;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton btnVentas;
    private javax.swing.JMenuItem buscarIdCliente;
    private javax.swing.JMenuItem buscarIdEmpleado;
    private javax.swing.JMenuItem buscarIdGenero;
    private javax.swing.JMenuItem buscarIdUsuario;
    private javax.swing.JMenuItem buscarIsbnLibro;
    private javax.swing.JMenuItem buscarNombreRol;
    private javax.swing.JMenuItem buscarNumeroPrestamo;
    private javax.swing.JMenuItem buscarNumeroVentas;
    private javax.swing.JMenuItem buscarTodosClientes;
    private javax.swing.JMenuItem buscarTodosEmpleados;
    private javax.swing.JMenuItem buscarTodosGeneros;
    private javax.swing.JMenuItem buscarTodosLibros;
    private javax.swing.JMenuItem buscarTodosPrestamos;
    private javax.swing.JMenuItem buscarTodosRol;
    private javax.swing.JMenuItem buscarTodosUsuarios;
    private javax.swing.JMenuItem buscarTodosVentas;
    private javax.swing.JMenu editarCliente;
    private javax.swing.JMenu editarEmpleado;
    private javax.swing.JMenu editarGenero;
    private javax.swing.JMenu editarLibro;
    private javax.swing.JMenu editarPrestamo;
    private javax.swing.JMenu editarRol;
    private javax.swing.JMenu editarUsuario;
    private javax.swing.JMenu editarVentas;
    public com.bolivia.label.CLabel fotoUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator21;
    private javax.swing.JPopupMenu.Separator jSeparator22;
    private javax.swing.JPopupMenu.Separator jSeparator23;
    private javax.swing.JPopupMenu.Separator jSeparator24;
    private javax.swing.JPopupMenu.Separator jSeparator25;
    private javax.swing.JPopupMenu.Separator jSeparator26;
    private javax.swing.JPopupMenu.Separator jSeparator27;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel menu;
    private javax.swing.JPopupMenu menuClientes;
    private javax.swing.JPopupMenu menuEmpleados;
    private javax.swing.JPopupMenu menuGenero;
    private javax.swing.JPopupMenu menuLibros;
    private javax.swing.JPopupMenu menuRol;
    private javax.swing.JPopupMenu menuUsuario;
    private javax.swing.JPopupMenu menuVentas;
    private javax.swing.JMenuItem nuevaVenta;
    private javax.swing.JMenuItem nuevoCliente;
    private javax.swing.JMenuItem nuevoEmpleado;
    private javax.swing.JMenuItem nuevoGenero;
    private javax.swing.JMenuItem nuevoLibro;
    private javax.swing.JMenuItem nuevoPrestamo;
    private javax.swing.JMenuItem nuevoRol;
    private javax.swing.JMenuItem nuevoUsuario;
    private javax.swing.JMenuItem verClientes;
    private javax.swing.JMenuItem verEmpleados;
    private javax.swing.JMenuItem verGeneros;
    private javax.swing.JMenuItem verLibros;
    private javax.swing.JMenuItem verPrestamos;
    private javax.swing.JMenuItem verRol;
    private javax.swing.JMenuItem verUsuarios;
    private javax.swing.JMenuItem verVentas;
    // End of variables declaration//GEN-END:variables
}
