/*
                                            funciones de la clase VentanaCliente
obtenerElementosVentana -> obtiene los elementos de los campos de la ventana y devuelve un objeto cliente
mostrarDatosVentana -> recibe un objeto cliente y llena los campos de la ventana
 */
package VISTA;

import MODELO.Cliente;
import MODELO_CONTROLADOR.funciones;
import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JSpinnerDateEditor;
import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author ayenni42
 */
public class ventanaCliente extends javax.swing.JDialog {

    /**
     * Creates new form ventanaCliente
     */
    public ventanaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        entId.setBackground(Color.WHITE);
        JCalendar calendario = entFecha.getJCalendar();
        calendario.setWeekOfYearVisible(false);
        calendario.setMaxDayCharacters(1);
        entFecha.setDate(funciones.fecha());
    }
    
    public Cliente obtenerElementosVentana () {
       String primerNombre = entPrimerNombre.getText();
       String segundoNombre = entSegundoNombre.getText();
       String apellidoPaterno = entApellidoPaterno.getText();
       String apellidoMaterno = entApellidoMaterno.getText();
       String cedula = entCedula.getText();
       String pais = entPais.getText();
       String ciudad = entCiudad.getText();
       String direccion = entDireccion.getText();
       String telefono = entTelefono.getText();
       String correo = entCorreo.getText();
       Date fechaRegistro = entFecha.getDate();
       Cliente cliente = new Cliente(primerNombre, segundoNombre, apellidoPaterno, apellidoMaterno, cedula, direccion, telefono, pais, ciudad, correo, fechaRegistro);
       return cliente;
    }
    
    public void mostrarDatosVentana (Cliente cliente) {
        entId.setText(String.valueOf(cliente.getId()));
        if (cliente.getNombre().isEmpty()) {
            entPrimerNombre.setText("Sin nombre");
        } else {
            entPrimerNombre.setText(cliente.getNombre());
        }
        if (cliente.getSegundoNombre().isEmpty()) {
            entSegundoNombre.setText("Sin Segundo Nombre");
        } else {
            entSegundoNombre.setText(cliente.getSegundoNombre());
        }
        if (cliente.getApellidoPaterno().isEmpty()) {
            entApellidoPaterno.setText("Sin Apellido Paterno");
        } else {
            entApellidoPaterno.setText(cliente.getApellidoPaterno());
        }
        if (cliente.getApellidoMaterno().isEmpty()) {
            entApellidoMaterno.setText("Sin Apellido Materno");
        } else {
            entApellidoMaterno.setText(cliente.getApellidoMaterno());
        }
        if (cliente.getCedula().isEmpty()) {
            entCedula.setText("Sin cedula");
        } else {
            entCedula.setText(cliente.getCedula());
        }
        if (cliente.getPais().isEmpty()) {
            entPais.setText("Sin Pais");
        } else {
            entPais.setText(cliente.getPais());
        }
        if (cliente.getCiudad().isEmpty()) {
            entCiudad.setText("Sin Ciudad");
        } else {
            entCiudad.setText(cliente.getCiudad());
        }
        if (cliente.getCorreo().isEmpty()) {
            entCorreo.setText("Sin Correo");
        } else {
            entCorreo.setText(cliente.getCorreo());
        }
        if (cliente.getTelefono().isEmpty()) {
            entTelefono.setText("Sin Telefono");
        } else {
            entTelefono.setText(cliente.getTelefono());
        } 
        
        if (cliente.getDireccion().isEmpty()) {
            entDireccion.setText("Sin Direccion");
        } else {
            entDireccion.setText(cliente.getDireccion());
        }
        if (cliente.getFechaRegistro() != null) {
            entFecha.setDate(cliente.getFechaRegistro());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        entId = new javax.swing.JTextField();
        entPrimerNombre = new javax.swing.JTextField();
        entSegundoNombre = new javax.swing.JTextField();
        entApellidoPaterno = new javax.swing.JTextField();
        entApellidoMaterno = new javax.swing.JTextField();
        entCedula = new javax.swing.JTextField();
        entDireccion = new javax.swing.JTextField();
        entTelefono = new javax.swing.JTextField();
        entCorreo = new javax.swing.JTextField();
        entCiudad = new javax.swing.JTextField();
        entPais = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        entFecha = new com.toedter.calendar.JDateChooser();
        barraProgreso = new javax.swing.JProgressBar();
        btnGuargar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        jLabel7.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel7.setText("SEGUNDO NOMBRE");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255)));
        jPanel1.setLayout(null);

        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(4, 4, 165, 215);

        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 13, 19, 30);

        jLabel3.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel3.setText("PRIMER NOMBRE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(174, 48, 145, 30);

        jLabel4.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel4.setText("APELLIDO PATERNO");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(174, 118, 165, 30);

        jLabel5.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel5.setText("APELLIDO MATERNO");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(174, 152, 169, 30);

        jLabel6.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel6.setText("SEGUNDO NOMBRE");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(174, 83, 153, 30);

        jLabel8.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel8.setText("CEDULA");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(174, 187, 65, 30);

        jLabel9.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel9.setText("DIRECCION ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(250, 227, 96, 30);

        jLabel10.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel10.setText("PAIS");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 227, 38, 30);

        jLabel11.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel11.setText("TELEFONO");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(250, 262, 85, 30);

        jLabel12.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel12.setText("CORREO");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 297, 67, 30);

        jLabel13.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel13.setText("FECHA REGISTRO");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 332, 143, 30);

        jLabel14.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel14.setText("CIUDAD");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 262, 63, 30);

        entId.setEnabled(false);
        jPanel1.add(entId);
        entId.setBounds(260, 13, 150, 30);
        jPanel1.add(entPrimerNombre);
        entPrimerNombre.setBounds(350, 48, 200, 30);
        jPanel1.add(entSegundoNombre);
        entSegundoNombre.setBounds(350, 82, 200, 30);
        jPanel1.add(entApellidoPaterno);
        entApellidoPaterno.setBounds(350, 118, 200, 30);
        jPanel1.add(entApellidoMaterno);
        entApellidoMaterno.setBounds(350, 152, 200, 30);
        jPanel1.add(entCedula);
        entCedula.setBounds(250, 187, 200, 30);
        jPanel1.add(entDireccion);
        entDireccion.setBounds(350, 227, 200, 30);
        jPanel1.add(entTelefono);
        entTelefono.setBounds(350, 262, 200, 30);
        jPanel1.add(entCorreo);
        entCorreo.setBounds(85, 297, 465, 30);
        jPanel1.add(entCiudad);
        entCiudad.setBounds(85, 262, 160, 30);
        jPanel1.add(entPais);
        entPais.setBounds(85, 227, 160, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(4, 222, 565, 10);
        jPanel1.add(entFecha);
        entFecha.setBounds(160, 332, 200, 30);
        jPanel1.add(barraProgreso);
        barraProgreso.setBounds(10, 372, 400, 30);

        btnGuargar.setText("GUAR");
        jPanel1.add(btnGuargar);
        btnGuargar.setBounds(495, 332, 70, 70);

        btnEditar.setText("EDIT");
        jPanel1.add(btnEditar);
        btnEditar.setBounds(420, 332, 70, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaCliente dialog = new ventanaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuargar;
    private javax.swing.JTextField entApellidoMaterno;
    private javax.swing.JTextField entApellidoPaterno;
    private javax.swing.JTextField entCedula;
    private javax.swing.JTextField entCiudad;
    private javax.swing.JTextField entCorreo;
    private javax.swing.JTextField entDireccion;
    private com.toedter.calendar.JDateChooser entFecha;
    private javax.swing.JTextField entId;
    private javax.swing.JTextField entPais;
    private javax.swing.JTextField entPrimerNombre;
    private javax.swing.JTextField entSegundoNombre;
    private javax.swing.JTextField entTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
