/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.Ordencompra;
import MODELO.Ordenprestamo;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author ayenni42
 */
public class ventanaVerGraficas extends javax.swing.JDialog {

    /**
     * Creates new form ventanaVerGraficas
     */
    ventanaMenu ventanaM;
    int opcion = 0;

    public ventanaVerGraficas(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rb2D.setEnabled(false);
        rb3D.setEnabled(false);
        rbBarra.setEnabled(false);
        rbCircular.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGraficas = new javax.swing.ButtonGroup();
        tipoGrafica = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rb3D = new javax.swing.JRadioButton();
        rb2D = new javax.swing.JRadioButton();
        rbBarra = new javax.swing.JRadioButton();
        rbCircular = new javax.swing.JRadioButton();
        btnGraficar = new javax.swing.JButton();
        nombreGrafica = new javax.swing.JLabel();
        grafica = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(null);

        rb3D.setBackground(new java.awt.Color(204, 204, 204));
        btnGraficas.add(rb3D);
        rb3D.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rb3D.setText("3D");
        jPanel1.add(rb3D);
        rb3D.setBounds(580, 10, 47, 30);

        rb2D.setBackground(new java.awt.Color(204, 204, 204));
        btnGraficas.add(rb2D);
        rb2D.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rb2D.setText("2D");
        jPanel1.add(rb2D);
        rb2D.setBounds(520, 10, 47, 30);

        rbBarra.setBackground(new java.awt.Color(204, 204, 204));
        tipoGrafica.add(rbBarra);
        rbBarra.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbBarra.setText("Barra");
        jPanel1.add(rbBarra);
        rbBarra.setBounds(720, 10, 70, 30);

        rbCircular.setBackground(new java.awt.Color(204, 204, 204));
        tipoGrafica.add(rbCircular);
        rbCircular.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbCircular.setText("Circular");
        jPanel1.add(rbCircular);
        rbCircular.setBounds(630, 10, 90, 30);

        btnGraficar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnGraficar.setText("Graficar");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGraficar);
        btnGraficar.setBounds(220, 480, 250, 30);

        nombreGrafica.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        nombreGrafica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreGrafica.setText("Grafica");
        jPanel1.add(nombreGrafica);
        nombreGrafica.setBounds(10, 10, 510, 30);
        jPanel1.add(grafica);
        grafica.setBounds(10, 40, 780, 430);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Enviar Grafica");
        jPanel1.add(jButton1);
        jButton1.setBounds(650, 480, 137, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        switch (opcion) {
            case 1:
                if (rb3D.isSelected() && rbBarra.isSelected()) {
                    DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
                    for (int i = 0; i < ventanaM.tablaLibros.getRowCount(); i++) {
                        dtsc.setValue(Integer.parseInt(ventanaM.tablaLibros.getValueAt(i, 2).toString()),
                                ventanaM.tablaLibros.getValueAt(i, 1).toString(),
                                ventanaM.tablaLibros.getValueAt(i, 3).toString());
                    }
                    JFreeChart ch = ChartFactory.createBarChart3D("Grafica de barras 3D", "Isbn", "Precio", dtsc, PlotOrientation.VERTICAL, true, true, false);
                    ChartPanel cp = new ChartPanel(ch);
                    cp.setBounds(20, 20, 690, 320);
                    grafica.add(cp);
                }
                if (rb3D.isSelected() && rbCircular.isSelected()) {
                    DefaultPieDataset dtsc = new DefaultPieDataset();

                    for (int i = 0; i < ventanaM.tablaLibros.getRowCount(); i++) {
                        dtsc.setValue(ventanaM.tablaLibros.getValueAt(i, 1).toString(),
                                Integer.parseInt(ventanaM.tablaLibros.getValueAt(i, 2).toString()));
                    }
                    JFreeChart ch = ChartFactory.createPieChart3D("Grafica Circular 3D", dtsc, true, true, false);
                    ChartPanel cp = new ChartPanel(ch);
                    add(cp);
                    cp.setBounds(10, 50, 450, 400);

                }
                if (rb2D.isSelected() && rbCircular.isSelected()) {
                    DefaultPieDataset dtsc = new DefaultPieDataset();

                    for (int i = 0; i < ventanaM.tablaLibros.getRowCount(); i++) {
                        dtsc.setValue(ventanaM.tablaLibros.getValueAt(i, 0).toString(),
                                Integer.parseInt(ventanaM.tablaLibros.getValueAt(i, 1).toString()));
                    }
                    JFreeChart ch = ChartFactory.createPieChart("Grafica Circular 2D", dtsc, true, true, false);
                    ChartPanel cp = new ChartPanel(ch);
                    add(cp);
                    cp.setBounds(10, 50, 450, 400);
                }

                break;
            case 2:

                ventanaVerOrdenCompra ventanaOC = new ventanaVerOrdenCompra(new javax.swing.JDialog(), true);

                if (rb3D.isSelected() && rbBarra.isSelected()) {
                    DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
                    for (int i = 0; i < ventanaOC.tablaNumeroOrden.getRowCount(); i++) {
                        dtsc.setValue(Integer.parseInt(ventanaOC.tablaNumeroOrden.getValueAt(i, 4).toString()),
                                ventanaOC.tablaNumeroOrden.getValueAt(i, 0).toString(),
                                ventanaOC.tablaNumeroOrden.getValueAt(i, 1).toString());
                    }
                    JFreeChart ch = ChartFactory.createBarChart3D("Grafica de barras 3D", "Isbn", "Cantidad", dtsc, PlotOrientation.VERTICAL, true, true, false);
                    ChartPanel cp = new ChartPanel(ch);
                    add(cp);
                    cp.setBounds(10, 50, 450, 400);

                }
                if (rb3D.isSelected() && rbCircular.isSelected()) {
                    DefaultPieDataset dtsc = new DefaultPieDataset();

                    for (int i = 0; i < ventanaOC.tablaNumeroOrden.getRowCount(); i++) {
                        dtsc.setValue(ventanaOC.tablaNumeroOrden.getValueAt(i, 0).toString(),
                                Integer.parseInt(ventanaOC.tablaNumeroOrden.getValueAt(i, 4).toString()));
                    }
                    JFreeChart ch = ChartFactory.createPieChart3D("Grafica Circular 3D", dtsc, true, true, false);
                    ChartPanel cp = new ChartPanel(ch);
                    add(cp);
                    cp.setBounds(10, 50, 450, 400);

                }
                if (rb2D.isSelected() && rbCircular.isSelected()) {
                    DefaultPieDataset dtsc = new DefaultPieDataset();

                    for (int i = 0; i < ventanaOC.tablaNumeroOrden.getRowCount(); i++) {
                        dtsc.setValue(ventanaOC.tablaNumeroOrden.getValueAt(i, 0).toString(),
                                Integer.parseInt(ventanaOC.tablaNumeroOrden.getValueAt(i, 4).toString()));
                    }
                    JFreeChart ch = ChartFactory.createPieChart("Grafica Circular 2D", dtsc, true, true, false);
                    ChartPanel cp = new ChartPanel(ch);
                    add(cp);
                    cp.setBounds(10, 50, 450, 400);
                }

                break;
            case 3:
                ventanaVerLibro ventanaVL = new ventanaVerLibro(new javax.swing.JDialog(), true);

                if (rb3D.isSelected() && rbBarra.isSelected()) {
                    DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
                    for (int i = 0; i < ventanaVL.tablaLibro.getRowCount(); i++) {
                        dtsc.setValue(Integer.parseInt(ventanaVL.tablaLibro.getValueAt(i, 5).toString()),
                                ventanaVL.tablaLibro.getValueAt(i, 2).toString(),
                                ventanaVL.tablaLibro.getValueAt(i, 3).toString());
                    }
                    JFreeChart ch = ChartFactory.createBarChart3D("Grafica de barras 3D", "Isbn", "Inventario", dtsc, PlotOrientation.VERTICAL, true, true, false);
                    ChartPanel cp = new ChartPanel(ch);
                    add(cp);
                    cp.setBounds(10, 50, 450, 400);

                }
                if (rb3D.isSelected() && rbCircular.isSelected()) {
                    DefaultPieDataset dtsc = new DefaultPieDataset();

                    for (int i = 0; i < ventanaVL.tablaLibro.getRowCount(); i++) {
                        dtsc.setValue(ventanaVL.tablaLibro.getValueAt(i, 0).toString(),
                                Integer.parseInt(ventanaVL.tablaLibro.getValueAt(i, 5).toString()));
                    }
                    JFreeChart ch = ChartFactory.createPieChart3D("Grafica Circular 3D", dtsc, true, true, false);
                    ChartPanel cp = new ChartPanel(ch);
                    add(cp);
                    cp.setBounds(10, 50, 450, 400);

                }
                if (rb2D.isSelected() && rbCircular.isSelected()) {
                    DefaultPieDataset dtsc = new DefaultPieDataset();

                    for (int i = 0; i < ventanaVL.tablaLibro.getRowCount(); i++) {
                        dtsc.setValue(ventanaVL.tablaLibro.getValueAt(i, 0).toString(),
                                Integer.parseInt(ventanaVL.tablaLibro.getValueAt(i, 5).toString()));
                    }
                    JFreeChart ch = ChartFactory.createPieChart("Grafica Circular 2D", dtsc, true, true, false);
                    ChartPanel cp = new ChartPanel(ch);
                    add(cp);
                    cp.setBounds(10, 50, 450, 400);
                }
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "Escoge Una Opción Valida");
        }
    }//GEN-LAST:event_btnGraficarActionPerformed

    public void graficaVentasSemana(JPanel panel, int w, int h) {
        DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
        for (int i = 0; i < ventanaM.tablaLibros.getRowCount(); i++) {
            dtsc.setValue(Integer.parseInt(ventanaM.tablaLibros.getValueAt(i, 2).toString()),
                    ventanaM.tablaLibros.getValueAt(i, 1).toString(),
                    ventanaM.tablaLibros.getValueAt(i, 3).toString());
        }
        JFreeChart ch = ChartFactory.createBarChart("Ventas De La Semana", "Fecha Venta", "Cantidad", dtsc, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel cp = new ChartPanel(ch);
        cp.setBounds(5, 5, w, h);
        panel.add(cp);
    }

    public void graficaOrdenCompra(List<Ordencompra> lista) {
        rb2D.setSelected(true);
        rbBarra.setSelected(true);
        DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
        SimpleDateFormat formato = new SimpleDateFormat("MM/dd/yyy");
        for (Ordencompra orden : lista) {
            dtsc.setValue(orden.getCantidadtotal(), orden.getPreciototal(), formato.format(orden.getFechaorden()));
        }
        JFreeChart ch = ChartFactory.createBarChart("Grafica de barras 2D", "Fecha", "Cantidad De Ventas", dtsc, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel cp = new ChartPanel(ch);
        cp.setBounds(3, 3, 780 - 6, 430);
        grafica.add(cp);
    }

    public void graficaOrdenPrestamo(List<Ordenprestamo> lista) {
        rb2D.setSelected(true);
        rbBarra.setSelected(true);
        DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
        SimpleDateFormat formato = new SimpleDateFormat("MM/dd/yyy");
        for (Ordenprestamo orden : lista) {
            dtsc.setValue(orden.getCantidadtotal(), orden.getCantidadtotal(), formato.format(orden.getFechaorden()));
        }
        JFreeChart ch = ChartFactory.createBarChart("Grafica de barras 2D", "Fecha", "Cantidad De Ventas", dtsc, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel cp = new ChartPanel(ch);
        cp.setBounds(3, 3, 780 - 6, 430);
        grafica.add(cp);
    }
    
    public void graficaInventarioLibro(ventanaVerLibro ventanaVL) {
        rb2D.setSelected(true);
        rbBarra.setSelected(true);
        DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
        for (int i = 0; i < ventanaVL.tablaLibro.getRowCount(); i++) {
            dtsc.setValue(Integer.parseInt(ventanaVL.tablaLibro.getValueAt(i, 4).toString()),
                    ventanaVL.tablaLibro.getValueAt(i, 5).toString(),
                    ventanaVL.tablaLibro.getValueAt(i, 2).toString());
        }
        JFreeChart ch = ChartFactory.createBarChart("Grafica de barras 2D", "Titulos", "Inventario", dtsc, PlotOrientation.HORIZONTAL, true, true, false);
        ChartPanel cp = new ChartPanel(ch);
        cp.setBounds(3, 3, 780 - 6, 430);
        grafica.add(cp);
    }

    public int getOpcion() {
        return opcion;
    }

    public void setOpcion(int opcion) {
        this.opcion = opcion;
    }

    public ventanaMenu getVentanaM() {
        return ventanaM;
    }

    public void setVentanaM(ventanaMenu ventanaM) {
        this.ventanaM = ventanaM;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaVerGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaVerGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaVerGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaVerGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaVerGraficas dialog = new ventanaVerGraficas(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraficar;
    private javax.swing.ButtonGroup btnGraficas;
    private javax.swing.JPanel grafica;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel nombreGrafica;
    private javax.swing.JRadioButton rb2D;
    private javax.swing.JRadioButton rb3D;
    private javax.swing.JRadioButton rbBarra;
    private javax.swing.JRadioButton rbCircular;
    private javax.swing.ButtonGroup tipoGrafica;
    // End of variables declaration//GEN-END:variables
}
